# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import itofin
from itofin import cashflows
from itofin import indexes
from itofin import models
from itofin import pricingengines
from itofin import processes
from itofin import results
from itofin import termstructures
from itofin import time
import typing
__all__ = [
    "CapFloor",
    "CapFloorType",
    "CreditDefaultSwap",
    "EuropeanExercise",
    "ForwardRateAgreement",
    "MakeCreditDefaultSwap",
    "MakeOis",
    "MakeSwaption",
    "MakeVanillaSwap",
    "MakeYoYInflationCapFloor",
    "OptionType",
    "OvernightIndexedSwap",
    "Position",
    "PricingModel",
    "ProtectionSide",
    "SettlementMethod",
    "SettlementType",
    "SwapType",
    "Swaption",
    "VanillaOption",
    "VanillaSwap",
    "YearOnYearInflationSwap",
    "YoYInflationCapFloor",
    "ZeroCouponInflationSwap",
]

@typing.final
class CapFloor:
    r"""
    A cap, floor or collar over a floating (ibor) leg.

    The constructor runs the standard market builder MakeCapFloor: its leg
    carries a unit nominal and one strike, and a zero forward_start excludes the
    spot caplet, so the leg is one coupon shorter than the schedule - that is
    what lets the cap price without a historical index fixing at the evaluation
    date.

    The cap/floor/collar staticmethods take an IborLeg the caller laid out
    instead and cap exactly it, spot caplet and all. They are the only route to
    a collar on this side, and the route a hand-built leg's own notional, day
    counter and fixing days reach the coupons by. Either way the core pads a
    short strike list across every coupon by repeating its last entry.

    Pricing needs an engine: call set_black_engine() before npv().
    """
    def __init__(self, cap_floor_type: CapFloorType, tenor: time.Period, ibor_index: indexes.IborIndex, strike: builtins.float, forward_start: time.Period, settings: itofin.Settings) -> None:
        r"""
        Build a standard market cap or floor through MakeCapFloor.

        Args:
            cap_floor_type (CapFloorType): Cap or Floor; the builder refuses
                Collar.
            tenor (Period): The length of the capped leg.
            ibor_index (IborIndex): The index the floating leg fixes off.
            strike (float): The single strike, padded across every coupon.
            forward_start (Period): The delay before the leg starts; a zero
                period excludes the spot caplet.
            settings (Settings): The explicit settings supplying the evaluation
                date and the stored fixings.

        Raises:
            ItofinError: If cap_floor_type is Collar, if the derived schedule
                is degenerate, or if the start has to be derived and no
                evaluation date is set.
        """
    @staticmethod
    def cap(leg: cashflows.IborLeg, cap_rates: typing.Sequence[builtins.float], settings: itofin.Settings) -> CapFloor:
        r"""
        Build a cap over the coupons leg builds, struck at cap_rates.

        Unlike the constructor this keeps whatever leg it is given: the spot
        caplet stays, and the leg's own notional, day counter and fixing days
        reach the coupons.

        Args:
            leg (IborLeg): The leg whose coupons are capped.
            cap_rates (list[float]): The cap strikes, padded to the leg length
                by repeating the last entry.
            settings (Settings): The explicit settings the instrument resolves
                its dates against.

        Returns:
            CapFloor: The cap over that leg.

        Raises:
            ItofinError: On an empty cap_rates list, or on whatever building
                the leg's coupons reports, a missing notional above all.
        """
    @staticmethod
    def floor(leg: cashflows.IborLeg, floor_rates: typing.Sequence[builtins.float], settings: itofin.Settings) -> CapFloor:
        r"""
        Build a floor over the coupons leg builds, struck at floor_rates.

        Args:
            leg (IborLeg): The leg whose coupons are floored.
            floor_rates (list[float]): The floor strikes, padded as cap() pads.
            settings (Settings): The explicit settings the instrument resolves
                its dates against.

        Returns:
            CapFloor: The floor over that leg.

        Raises:
            ItofinError: Fallible as cap(), on an empty list or a leg whose
                coupons cannot be built.
        """
    @staticmethod
    def collar(leg: cashflows.IborLeg, cap_rates: typing.Sequence[builtins.float], floor_rates: typing.Sequence[builtins.float], settings: itofin.Settings) -> CapFloor:
        r"""
        Build a collar: long the cap at cap_rates, short the floor at floor_rates.

        The collar is worth the one less the other, and this is the only route
        to one over a floating leg.

        Args:
            leg (IborLeg): The leg whose coupons are collared.
            cap_rates (list[float]): The cap strikes, padded as cap() pads.
            floor_rates (list[float]): The floor strikes, padded the same way.
            settings (Settings): The explicit settings the instrument resolves
                its dates against.

        Returns:
            CapFloor: The collar over that leg.

        Raises:
            ItofinError: On either list being empty, both being required, or on
                a leg whose coupons cannot be built.
        """
    def cap_rates(self) -> builtins.list[builtins.float]:
        r"""
        Return the cap strikes, one per coupon.

        Returns:
            list[float]: The cap strikes; empty for a floor.
        """
    def floor_rates(self) -> builtins.list[builtins.float]:
        r"""
        Return the floor strikes, one per coupon.

        Returns:
            list[float]: The floor strikes; empty for a cap.
        """
    def coupon_count(self) -> builtins.int:
        r"""
        Return the number of optionlets.

        Returns:
            int: One per floating coupon on the leg.
        """
    def set_black_engine(self, engine: pricingengines.BlackCapFloorEngine) -> None:
        r"""
        Attach a Black engine, pricing each optionlet off a volatility surface.

        The engine is built separately, so the same one can be shared across
        instruments. It must resolve its dates against the same Settings object
        as this cap/floor: two different settings would price the leg and the
        optionlets on different dates with no error raised.

        Args:
            engine (BlackCapFloorEngine): The engine and its optionlet
                volatility surface.
        """
    def calculate(self) -> None:
        r"""
        Force the valuation. Idempotent.

        Raises:
            ItofinError: If no engine is attached, no evaluation date is set,
                or the engine refuses the instrument.
        """
    def is_calculated(self) -> builtins.bool:
        r"""
        Return whether the cached results are currently valid.

        The Black engine observes its volatility handle, so moving a quote the
        engine was built over reaches the cap and flips this back to False.

        Returns:
            bool: True when the next accessor reads the cache.
        """
    def price(self, engine: pricingengines.BlackCapFloorEngine) -> builtins.float:
        r"""
        Attach engine and return the NPV.

        Args:
            engine (BlackCapFloorEngine): The engine to install and price on.

        Returns:
            float: The cap/floor value.

        Raises:
            ItofinError: On anything that makes the valuation fail.
        """
    def results(self) -> results.Results:
        r"""
        Return a frozen snapshot of the valuation, calculating first.

        Returns:
            Results: A copy of the valuation results.

        Raises:
            ItofinError: On anything that makes the valuation fail.
        """
    def npv(self) -> builtins.float:
        r"""
        Return the cap/floor NPV under the attached engine.

        Returns:
            float: The present value.

        Raises:
            ItofinError: If no engine is attached, which the core reports as
                "null pricing engine".
        """

@typing.final
class CreditDefaultSwap:
    r"""
    A credit-default swap quoted as a running spread.

    __init__ takes the C++ default terms with settles_accrual and
    pays_at_default_time quoted; with_terms additionally exposes
    protection_start and rebates_accrual.

    These direct constructors keep the remaining CdsTerms fields at their core
    defaults: claim (a face-value claim, which needs a claim facade that does
    not exist yet), last_period_day_counter, upfront_date and
    cash_settlement_days. trade_date and an upfront are not set here but are
    reachable through MakeCreditDefaultSwap (with_trade_date and the upfront_rate
    constructor argument).

    Pricing needs an engine: call set_engine() or set_isda_engine() before
    npv().
    """
    def __init__(self, side: ProtectionSide, notional: builtins.float, spread: builtins.float, schedule: time.Schedule, payment_convention: time.BusinessDayConvention, day_counter: time.DayCounter, settles_accrual: builtins.bool, pays_at_default_time: builtins.bool, settings: itofin.Settings) -> None:
        r"""
        Build a contract on the C++ default terms.

        Args:
            side (ProtectionSide): Whether protection is bought or sold.
            notional (float): The notional the premium and protection are
                quoted on.
            spread (float): The running spread the premium leg pays.
            schedule (Schedule): The premium leg's payment schedule.
            payment_convention (BusinessDayConvention): The roll applied to the
                premium payment dates.
            day_counter (DayCounter): The day count the premium accrues on.
            settles_accrual (bool): Whether the accrued coupon settles on
                default.
            pays_at_default_time (bool): Whether the protection pays at default
                rather than at maturity.
            settings (Settings): The explicit settings supplying the evaluation
                date the contract prices against.

        Raises:
            ItofinError: If the schedule is empty, if the protection start
                follows the first accrual date under a pre-Big-Bang
                date-generation rule, or if the premium leg cannot be built.
        """
    @staticmethod
    def with_terms(side: ProtectionSide, notional: builtins.float, spread: builtins.float, schedule: time.Schedule, payment_convention: time.BusinessDayConvention, day_counter: time.DayCounter, settings: itofin.Settings, protection_start: typing.Optional[time.Date] = None, settles_accrual: builtins.bool = True, pays_at_default_time: builtins.bool = True, rebates_accrual: builtins.bool = True) -> CreditDefaultSwap:
        r"""
        Build a contract quoting the terms __init__ defaults.

        The three flags carry the core defaults verbatim, so calling this with
        only the positional arguments builds exactly what __init__ builds.

        Args:
            side (ProtectionSide): Whether protection is bought or sold.
            notional (float): The notional the premium and protection are
                quoted on.
            spread (float): The running spread the premium leg pays.
            schedule (Schedule): The premium leg's payment schedule.
            payment_convention (BusinessDayConvention): The roll applied to the
                premium payment dates.
            day_counter (DayCounter): The day count the premium accrues on.
            settings (Settings): The explicit settings; it precedes the
                defaulted terms because a Python signature cannot put a
                required argument after an optional one.
            protection_start (Date | None): The first date a default triggers
                the contract; None takes the schedule's first date, which is
                what __init__ does.
            settles_accrual (bool): Whether the accrued coupon settles on
                default.
            pays_at_default_time (bool): Whether the protection pays at default
                rather than at maturity.
            rebates_accrual (bool): Whether the protection seller rebates the
                accrued current coupon.

        Returns:
            CreditDefaultSwap: The contract on those terms.

        Raises:
            ItofinError: On the same conditions __init__ reports.
        """
    def set_engine(self, engine: pricingengines.MidPointCdsEngine) -> None:
        r"""
        Attach a mid-point engine so the contract prices.

        The engine is built separately, so one engine can be shared across
        contracts. It must resolve its dates against the same Settings object
        as this contract.

        Args:
            engine (MidPointCdsEngine): The engine and its default-probability
                and discount curves.
        """
    def set_isda_engine(self, engine: pricingengines.IsdaCdsEngine) -> None:
        r"""
        Attach an ISDA engine so the contract prices under the standard model.

        A separate setter rather than a widened set_engine: the two engine
        facades are unrelated classes, so one argument cannot name both. The
        same sharing and same-Settings rules apply, and the ISDA engine
        additionally refuses curves outside its specification when the contract
        prices.

        Args:
            engine (IsdaCdsEngine): The ISDA engine and its curves.
        """
    def calculate(self) -> None:
        r"""
        Force the valuation. Idempotent.

        Raises:
            ItofinError: If no engine is attached, no evaluation date is set,
                or the engine refuses the contract.
        """
    def is_calculated(self) -> builtins.bool:
        r"""
        Return whether the cached results are currently valid.

        Returns:
            bool: True when the next accessor reads the cache.
        """
    def price(self, engine: pricingengines.MidPointCdsEngine) -> builtins.float:
        r"""
        Attach the mid-point engine and return the NPV.

        set_engine followed by npv, in one call. The mid-point engine is the
        primary because it is the core's own default CDS engine;
        set_isda_engine stays a separate setter.

        Args:
            engine (MidPointCdsEngine): The engine to install and price on.

        Returns:
            float: The contract value.

        Raises:
            ItofinError: On anything that makes the valuation fail.
        """
    def results(self) -> results.Results:
        r"""
        Return a frozen snapshot of the valuation, calculating first.

        Returns:
            Results: A copy of the valuation results.

        Raises:
            ItofinError: On anything that makes the valuation fail.
        """
    def npv(self) -> builtins.float:
        r"""
        Return the contract NPV under the attached engine.

        Returns:
            float: The present value.

        Raises:
            ItofinError: If no engine is attached, which the core reports as
                "null pricing engine".
        """
    def fair_spread(self) -> builtins.float:
        r"""
        Return the running spread that prices the contract at zero.

        Returns:
            float: The fair running spread.

        Raises:
            ItofinError: If no engine is attached, and when the engine priced a
                worthless premium leg and so provided no fair spread.
        """
    def fair_upfront(self) -> builtins.float:
        r"""
        Return the upfront that prices the contract at zero.

        Returns:
            float: The fair upfront, as a fraction of the notional.

        Raises:
            ItofinError: On the same conditions fair_spread reports.
        """
    def notional(self) -> builtins.float:
        r"""
        Return the notional the premium and the protection are quoted on.

        Returns:
            float: The contract notional.
        """
    def protection_end_date(self) -> time.Date:
        r"""
        Return the final premium coupon's accrual end before payment adjustment.

        Returns:
            Date: The final date covered by protection.

        Raises:
            ItofinError: If the premium leg has no final coupon.
        """
    def accrual_rebate_amount(self) -> typing.Optional[builtins.float]:
        r"""
        Return the accrued coupon the protection seller rebates.

        A contract traded in the past still carries the flow: the core builds
        it whenever the flag is set, regardless of the trade date, so None here
        means the flag was off, never a stale trade. Such a flow carries a real
        accrued amount but settled on a past date, so it no longer reaches the
        value. The amount is returned bare rather than behind a cash-flow
        facade, there being none.

        Returns:
            float | None: The rebated amount, or None when the contract does
                not rebate accrual at all.
        """
    def accrual_rebate_date(self) -> typing.Optional[time.Date]:
        r"""
        Return the date the accrual rebate settles on.

        Returns:
            Date | None: The cash-settlement date the upfront also pays on, or
                None on the same terms as accrual_rebate_amount.
        """
    def coupon_leg_npv(self) -> builtins.float:
        r"""
        Return the premium leg's NPV.

        Returns:
            float: The present value of the premium leg.

        Raises:
            ItofinError: On the same conditions fair_spread reports.
        """
    def default_leg_npv(self) -> builtins.float:
        r"""
        Return the protection leg's NPV.

        Returns:
            float: The present value of the protection leg.

        Raises:
            ItofinError: On the same conditions fair_spread reports.
        """
    def implied_hazard_rate(self, target_npv: builtins.float, discount: termstructures.YieldTermStructure, day_counter: time.DayCounter, recovery_rate: builtins.float, accuracy: builtins.float, model: PricingModel) -> builtins.float:
        r"""
        Return the flat hazard rate at which this contract is worth target_npv.

        The solve stands on its own engine rather than on whichever one
        set_engine attached: it builds a flat, quote-backed probability curve
        and prices on model against discount. There is therefore no
        probability-curve argument - the curve being solved for is the one the
        core builds.

        Args:
            target_npv (float): The value the contract is solved to.
            discount (YieldTermStructure): The curve the flows discount on.
            day_counter (DayCounter): The day count of the internal flat curve,
                not of the contract. Under PricingModel.Isda both it and
                discount must count Act/365 (Fixed), which is what the ISDA
                engine requires of its curves.
            recovery_rate (float): The recovery assumed on default.
            accuracy (float): The tolerance the solve stops at, on the rate.
            model (PricingModel): The model the contract is inverted under.

        Returns:
            float: The flat hazard rate.

        Raises:
            ItofinError: On a malformed contract, and when the solve does not
                converge, which includes a pricing failure at some hazard rate.
        """

@typing.final
class EuropeanExercise:
    r"""
    A single-date exercise schedule.

    Held as the exercise trait object the swaption constructor takes, so the
    same value reaches the instrument.
    """
    def __init__(self, date: time.Date) -> None:
        r"""
        Build the exercise schedule.

        Args:
            date (Date): The single date the option may be exercised on.
        """

@typing.final
class ForwardRateAgreement:
    r"""
    A forward rate agreement over an Ibor index.

    The FRA prices without an engine, so the valuation accessors work as soon
    as it is built. It settles and expires on its value date - the day the
    underlying loan begins - not on the later maturity date.

    Passing None for the discount curve discounts on the forwarding curve
    instead.
    """
    def __init__(self, index: indexes.IborIndex, value_date: time.Date, fra_type: Position, strike_forward_rate: builtins.float, notional_amount: builtins.float, discount_curve: typing.Optional[termstructures.YieldTermStructure]) -> None:
        r"""
        Build the indexed-coupon FRA.

        The maturity is the index's own maturity of the value date and the
        forward rate is the index fixing.

        Args:
            index (IborIndex): The index the forward rate is forecast by.
            value_date (Date): The day the underlying loan begins.
            fra_type (Position): The side taken, Long or Short.
            strike_forward_rate (float): The simple rate agreed on.
            notional_amount (float): The notional the settlement accrues on.
            discount_curve (YieldTermStructure | None): The curve the
                settlement discounts on; None discounts on the index's
                forwarding curve instead.

        Raises:
            ItofinError: If the notional is not positive or the maturity
                cannot be derived from the value date.
        """
    @staticmethod
    def with_maturity(index: indexes.IborIndex, value_date: time.Date, maturity_date: time.Date, fra_type: Position, strike_forward_rate: builtins.float, notional_amount: builtins.float, discount_curve: typing.Optional[termstructures.YieldTermStructure]) -> ForwardRateAgreement:
        r"""
        Build the FRA over an explicit [value_date, maturity_date] window.

        The forward rate is the par approximation off the index's forwarding
        curve; the maturity is adjusted on the index's fixing calendar under
        the index's convention.

        Args:
            index (IborIndex): The index supplying the forwarding curve and
                the conventions.
            value_date (Date): The day the underlying loan begins.
            maturity_date (Date): The day the underlying loan ends, before
                adjustment.
            fra_type (Position): The side taken, Long or Short.
            strike_forward_rate (float): The simple rate agreed on.
            notional_amount (float): The notional the settlement accrues on.
            discount_curve (YieldTermStructure | None): The curve the
                settlement discounts on; None discounts on the index's
                forwarding curve instead.

        Returns:
            ForwardRateAgreement: The explicit-window FRA.

        Raises:
            ItofinError: If the notional is not positive or the value date is
                not earlier than the adjusted maturity date.
        """
    def forward_rate(self) -> builtins.float:
        r"""
        Return the forward rate associated with the FRA term.

        Returns:
            float: The simple forward rate over the FRA window.

        Raises:
            ItofinError: If the index has no forwarding curve or fixing
                covering the term.
        """
    def amount(self) -> builtins.float:
        r"""
        Return the payoff on the value date.

        Returns:
            float: The settlement amount, signed by the position.

        Raises:
            ItofinError: On an expired FRA, which has no settlement amount.
        """
    def npv(self) -> builtins.float:
        r"""
        Return the settlement amount discounted to the value date.

        Discounts on the discount curve, or on the index's forwarding curve
        when none was given.

        Returns:
            float: The present value.

        Raises:
            ItofinError: If no evaluation date is set or the curves cannot
                cover the term.
        """
    def value_date(self) -> time.Date:
        r"""
        Return the day the underlying loan begins.

        The FRA settles and expires on this date.

        Returns:
            Date: The value date.
        """
    def maturity_date(self) -> time.Date:
        r"""
        Return the day the underlying loan ends.

        Adjusted on the index's fixing calendar under the index's convention.

        Returns:
            Date: The adjusted maturity date.
        """

@typing.final
class MakeCreditDefaultSwap:
    r"""
    Market-convention builder for a CreditDefaultSwap: derives the premium
    schedule from a maturity and the post-Big-Bang CDS conventions, and takes
    the trade date from the evaluation date settings carries.

    An unset optional keeps the core default: a Buyer side, a nominal of 1, no
    upfront, a 3M coupon tenor, the pre-CDS2015 DateGeneration.CDS rule, a
    Following roll, an Act/360 day counter and three cash-settlement days. Only
    the term-date quotation is exposed; the tenor and explicit-schedule ones and
    the accrual-rebate flag are not, the latter being reachable through
    CreditDefaultSwap.with_terms.

    Each build() runs a fresh chain, so one builder object cannot carry a
    setting into a later contract.
    """
    def __init__(self, term_date: time.Date, running_spread: builtins.float, settings: itofin.Settings, nominal: typing.Optional[builtins.float] = None, upfront_rate: typing.Optional[builtins.float] = None, side: typing.Optional[ProtectionSide] = None, trade_date: typing.Optional[time.Date] = None) -> None:
        r"""
        Store the configuration the chain is assembled from in build().

        Each build() runs a fresh chain, so one builder object cannot carry a
        setting into a later contract.

        Args:
            term_date (Date): The maturity the premium schedule is derived
                from.
            running_spread (float): The running spread the premium leg pays.
            settings (Settings): The explicit settings supplying the evaluation
                date the trade is dated off.
            nominal (float | None): The notional; None keeps the core default
                of 1.
            upfront_rate (float | None): The upfront as a fraction of the
                notional; None keeps the core default of none.
            side (ProtectionSide | None): Which side the contract holds; None
                keeps the core default of Buyer.
            trade_date (Date | None): Overrides the evaluation date the trade
                is otherwise dated off, which is how a contract traded in the
                past is built.
        """
    def build(self) -> CreditDefaultSwap:
        r"""
        Build the contract, which carries no engine.

        Attach one with set_engine or set_isda_engine before pricing.

        Returns:
            CreditDefaultSwap: The contract on the market conventions.

        Raises:
            ItofinError: If no evaluation date is set, the trade date being
                derived from it, and on whatever the contract construction
                rejects.
        """

@typing.final
class MakeOis:
    r"""
    Market-convention builder for an OvernightIndexedSwap.

    Derives the start and end dates, both schedules and the discounting engine
    from a swap tenor and an overnight index, so the caller states conventions
    instead of hand-building two schedules. ``fixed_rate=None`` builds a par
    swap: the fair rate is computed off a temporary swap and written into the
    fixed leg, so the result prices to a zero NPV.

    The core builder is a consumed-self fluent chain, which does not cross the
    FFI boundary; this facade takes the overrides as constructor keywords and
    assembles the chain inside build(). Unexposed core overrides keep their defaults;
    the four the core rejects outright
    (telescopic value dates, lookback, lockout and observation shift) are
    unreachable from here by construction. The built swap already carries its
    DiscountingSwapEngine.
    """
    def __init__(self, swap_tenor: time.Period, overnight_index: indexes.OvernightIndex, settings: itofin.Settings, fixed_rate: typing.Optional[builtins.float] = None, forward_start: typing.Optional[time.Period] = None, effective_date: typing.Optional[time.Date] = None, nominal: typing.Optional[builtins.float] = None, payment_lag: typing.Optional[builtins.int] = None, discounting_term_structure: typing.Optional[termstructures.YieldTermStructure] = None, averaging_method: typing.Optional[termstructures.RateAveraging] = None, fixed_leg_day_count: typing.Optional[time.DayCounter] = None) -> None:
        r"""
        Store the configuration the chain is assembled from in build().

        Args:
            swap_tenor (Period): The length of the swap.
            overnight_index (OvernightIndex): The index the overnight leg
                averages or compounds.
            settings (Settings): The explicit settings supplying the evaluation
                date and the stored fixings.
            fixed_rate (float | None): The rate of the fixed leg; None builds a
                par swap.
            forward_start (Period | None): The delay before the swap starts;
                None starts it spot, at a zero-day period.
            effective_date (Date | None): The start date; None derives it from
                the evaluation date.
            nominal (float | None): The notional; None keeps the core default.
            payment_lag (int | None): The days between accrual end and payment;
                None keeps the core default.
            discounting_term_structure (YieldTermStructure | None): The curve
                the flows discount on; None keeps the core default.
            fixed_leg_day_count (DayCounter | None): Override the fixed-leg day count.
            averaging_method (RateAveraging | None): Whether the overnight
                fixings compound or are averaged; None keeps the core default.
        """
    def build(self) -> OvernightIndexedSwap:
        r"""
        Build the priced swap.

        Returns:
            OvernightIndexedSwap: The swap, already carrying its discounting
                engine.

        Raises:
            ItofinError: If effective_date is unset and no evaluation date is
                set to derive the start from; if the schedule or the overnight
                leg is degenerate; or if the par-rate fill fails to price.
        """

@typing.final
class MakeSwaption:
    r"""
    Build a payer vanilla swaption from a SwapIndex and exactly one option date source.

    Specify option_tenor or fixing_date. A missing strike requests the forward
    swap's fair rate. Overnight swap indexes and underlying-type selection are
    not supported. Attach a pricing engine to the resulting Swaption separately.
    """
    def __init__(self, swap_index: indexes.SwapIndex, option_tenor: typing.Optional[time.Period] = None, strike: typing.Optional[builtins.float] = None, *, fixing_date: typing.Optional[time.Date] = None, nominal: builtins.float = 1.0, settlement_type: SettlementType = SettlementType.Physical, settlement_method: SettlementMethod = SettlementMethod.PhysicalOTC, option_convention: time.BusinessDayConvention = time.BusinessDayConvention.ModifiedFollowing, exercise_date: typing.Optional[time.Date] = None, exercise_calendar: typing.Optional[time.Calendar] = None, indexed_coupons: typing.Optional[builtins.bool] = None) -> None:
        r"""
        Retain the index and overrides for repeatable build calls.
        """
    def build(self) -> Swaption:
        r"""
        Build the swaption, propagating date, forwarding and coupon-setting errors.
        """

@typing.final
class MakeVanillaSwap:
    r"""
    Market-convention builder for a VanillaSwap.

    Derives the start and end dates, both schedules, the fixed-leg tenor and
    day count and the discounting engine from a swap tenor and an Ibor index,
    so the caller states conventions instead of hand-building two schedules.
    ``fixed_rate=None`` builds a par swap: the fair rate is computed and written
    into the fixed leg, so the result prices to a zero NPV.

    The core builder is a consumed-self fluent chain, which does not cross the
    FFI boundary; this facade takes the overrides as constructor keywords and
    assembles the chain inside build(). Only four overrides are exposed; every
    other core one keeps its default, so the discounting curve is always the
    index's forwarding curve. The built swap already carries its
    DiscountingSwapEngine.
    """
    def __init__(self, swap_tenor: time.Period, ibor_index: indexes.IborIndex, settings: itofin.Settings, fixed_rate: typing.Optional[builtins.float] = None, forward_start: typing.Optional[time.Period] = None, effective_date: typing.Optional[time.Date] = None, nominal: typing.Optional[builtins.float] = None, fixed_leg_tenor: typing.Optional[time.Period] = None, fixed_leg_day_count: typing.Optional[time.DayCounter] = None) -> None:
        r"""
        Store the configuration the chain is assembled from in build().

        Args:
            swap_tenor (Period): The length of the swap.
            ibor_index (IborIndex): The index the floating leg fixes off, and
                whose forwarding curve discounts.
            settings (Settings): The explicit settings supplying the evaluation
                date and the stored fixings.
            fixed_rate (float | None): The rate of the fixed leg; None builds a
                par swap.
            forward_start (Period | None): The delay before the swap starts;
                None starts it spot, at a zero-day period.
            effective_date (Date | None): The start date; None derives it from
                the evaluation date.
            nominal (float | None): The notional; None keeps the core default.
            fixed_leg_tenor (Period | None): The fixed-leg payment tenor; None
                takes the currency's market convention.
            fixed_leg_day_count (DayCounter | None): The fixed-leg day count;
                None takes the currency's market convention.
        """
    def build(self) -> VanillaSwap:
        r"""
        Build the priced swap.

        Returns:
            VanillaSwap: The swap, already carrying its discounting engine.

        Raises:
            ItofinError: If effective_date is unset and no evaluation date is
                set to derive the start from; if the index is neither EUR nor
                USD, the two the fixed-leg defaults are known for; or if the
                par-rate fill fails to price.
        """

@typing.final
class MakeYoYInflationCapFloor:
    r"""
    The standard market builder for a year-on-year inflation cap or floor.

    It derives an annual year-on-year leg from a length in years, trims that leg
    to the optionlets asked for, and strikes it either at an explicit strike or
    at the money off atm_strike. Exactly one of the two is required: the core
    refuses both together and neither at all, at build time rather than at the
    setters, so both surface from build().

    The core builder is a consumed-self fluent chain, which does not cross the
    FFI boundary; this facade takes the whole configuration up front and
    assembles the chain inside build(), as MakeVanillaSwap does. An unset
    optional leaves the core default in place: a 1,000,000 nominal, a
    ModifiedFollowing payment roll, a 30/360 bond-basis day counter, no fixing
    days, every optionlet kept and no forward start.

    Trimming happens before the at-the-money fill, so as_optionlet and
    first_caplet_excluded change what an unset strike resolves to: the rate that
    reprices whatever survives, not the whole leg's.

    CapFloorType.Collar has no path here - the builder carries a single strike,
    and a collar needs two strike vectors - so a collar is built through
    YoYInflationCapFloor.collar over a leg of its own instead.
    """
    def __init__(self, cap_floor_type: CapFloorType, index: indexes.YoYInflationIndex, length: builtins.int, calendar: time.Calendar, observation_lag: time.Period, interpolation: indexes.CpiInterpolationType, settings: itofin.Settings, nominal: typing.Optional[builtins.float] = None, effective_date: typing.Optional[time.Date] = None, payment_day_counter: typing.Optional[time.DayCounter] = None, payment_adjustment: typing.Optional[time.BusinessDayConvention] = None, fixing_days: typing.Optional[builtins.int] = None, engine: typing.Optional[pricingengines.YoYInflationCapFloorEngine] = None, as_optionlet: builtins.bool = False, forward_start: typing.Optional[time.Period] = None, first_caplet_excluded: builtins.bool = False, strike: typing.Optional[builtins.float] = None, atm_strike: typing.Optional[termstructures.YieldTermStructure] = None) -> None:
        r"""
        Store the configuration the chain is assembled from in build().

        Args:
            cap_floor_type (CapFloorType): Cap or Floor; Collar has no path
                here.
            index (YoYInflationIndex): The index the optionlets fix off.
            length (int): The length of the derived annual leg, in years.
            calendar (Calendar): The calendar the payments roll on.
            observation_lag (Period): How far back each coupon's fixings are
                observed.
            interpolation (CpiInterpolationType): How the observed fixings are
                interpolated.
            settings (Settings): The explicit settings supplying the evaluation
                date and the stored fixings.
            nominal (float | None): The notional; None keeps the core default
                of 1,000,000.
            effective_date (Date | None): The start date; None derives it from
                the evaluation date.
            payment_day_counter (DayCounter | None): The day count; None keeps
                the core default of 30/360 bond basis.
            payment_adjustment (BusinessDayConvention | None): The payment
                roll; None keeps the core default of ModifiedFollowing.
            fixing_days (int | None): The fixing days of the coupons; None
                keeps the core default of none.
            engine (YoYInflationCapFloorEngine | None): An engine installed on
                the built instrument; None leaves it unpriced.
            as_optionlet (bool): Whether to keep only the last optionlet.
            forward_start (Period | None): The delay before the leg starts;
                None keeps the core default of no forward start.
            first_caplet_excluded (bool): Whether to drop the front optionlet.
            strike (float | None): The explicit strike; exactly one of this and
                atm_strike is required.
            atm_strike (YieldTermStructure | None): The curve the at-the-money
                strike is filled off; exactly one of this and strike is
                required.
        """
    def build(self) -> YoYInflationCapFloor:
        r"""
        Build the cap/floor, which already carries its engine when one was given.

        Returns:
            YoYInflationCapFloor: The built instrument.

        Raises:
            ItofinError: If both strike and atm_strike are given or neither is;
                if the start date has to be derived and no evaluation date is
                set; and on whatever the leg construction and the at-the-money
                fill report.
        """

@typing.final
class OvernightIndexedSwap:
    r"""
    A fixed leg versus a simple-averaged or compounded overnight leg.

    Only MakeOis builds one, so it always arrives priced; there is no
    set_engine and no raw constructor (both deferred with the two-schedule
    master ctor).
    """
    def fair_rate(self) -> builtins.float:
        r"""
        Return the fixed rate that zeroes the swap NPV.

        Returns:
            float: The fair fixed rate, read through the swap's base.

        Raises:
            ItofinError: If the swap has expired or its engine fails to price.
        """
    def calculate(self) -> None:
        r"""
        Force the valuation. Idempotent.

        Raises:
            ItofinError: If no evaluation date is set or the engine refuses the
                swap.
        """
    def is_calculated(self) -> builtins.bool:
        r"""
        Return whether the cached results are currently valid.

        Returns:
            bool: True when the next accessor reads the cache.
        """
    def price(self) -> builtins.float:
        r"""
        Price the swap and return the NPV.

        The only no-argument price(): MakeOis already attached the discounting
        engine, so none is left to install.

        Returns:
            float: The present value.

        Raises:
            ItofinError: On anything that makes the valuation fail, including
                the "null pricing engine" a swap that somehow arrived without
                one reports.
        """
    def results(self) -> results.Results:
        r"""
        Return a frozen snapshot of the valuation, calculating first.

        Returns:
            Results: A copy of the valuation results.

        Raises:
            ItofinError: On anything that makes the valuation fail.
        """
    def npv(self) -> builtins.float:
        r"""
        Return the swap NPV under the engine the builder attached.

        Returns:
            float: The present value.

        Raises:
            ItofinError: On anything that makes the valuation fail.
        """
    def nominal(self) -> builtins.float:
        r"""
        Return the notional both legs accrue on.

        Returns:
            float: The single nominal, read through the swap's base.

        Raises:
            ItofinError: If the legs carry per-coupon nominals, which leaves no
                single one to report.
        """
    def fixed_rate(self) -> builtins.float:
        r"""
        Return the fixed-leg rate.

        Returns:
            float: The rate given to the builder, or the fair rate it filled in
                for a par swap.
        """

@typing.final
class Swaption:
    r"""
    A European option to enter a vanilla or overnight swap.

    The swaption registers with the underlying swap and with the evaluation
    date on the Settings it was built with (D5). Pricing needs an engine: call
    one of the three setters before npv.
    """
    def __init__(self, swap: VanillaSwap, exercise: EuropeanExercise, settlement_type: SettlementType, settlement_method: SettlementMethod, settings: itofin.Settings) -> None:
        r"""
        Build the swaption over swap.

        Args:
            swap (VanillaSwap): The swap the option enters; it needs no
                discounting engine of its own, the swaption engine reading its
                arguments instead.
            exercise (EuropeanExercise): The single exercise date.
            settlement_type (SettlementType): Whether exercise settles
                physically or in cash.
            settlement_method (SettlementMethod): The mechanics under that
                type; an inconsistent pair surfaces from npv(), not here.
            settings (Settings): The explicit settings supplying the evaluation
                date the swaption prices against.
        """
    @staticmethod
    def from_ois(swap: OvernightIndexedSwap, exercise: EuropeanExercise, settlement_type: SettlementType, settlement_method: SettlementMethod, settings: itofin.Settings) -> Swaption:
        r"""
        Build an option on an overnight swap, retaining the same shared underlying.
        """
    def exercise_date(self) -> time.Date:
        r"""
        Return the single European exercise date.
        """
    def underlying_fixed_rate(self) -> builtins.float:
        r"""
        Return the underlying swap's fixed rate.
        """
    def underlying_nominal(self) -> builtins.float:
        r"""
        Return the underlying swap's nominal.
        """
    def set_jamshidian_engine(self, model: models.HullWhite) -> None:
        r"""
        Attach a Jamshidian engine so the swaption prices off Hull-White.

        The engine is European-only: a non-European exercise errors at pricing
        time.

        Args:
            model (HullWhite): The short-rate model supplying the dynamics.
        """
    def set_black_engine(self, engine: pricingengines.BlackSwaptionEngine) -> None:
        r"""
        Attach a Black engine, pricing off a swaption volatility surface.

        The engine is built separately, so the same one can be shared across
        swaptions. It must carry the same Settings object as this swaption: two
        different settings would price the swap and the option on different
        dates with no error raised.

        Args:
            engine (BlackSwaptionEngine): The engine and its volatility
                surface.
        """
    def set_bachelier_engine(self, engine: pricingengines.BachelierSwaptionEngine) -> None:
        r"""
        Attach a Bachelier engine, pricing off a normal-volatility surface.

        The same-Settings requirement as set_black_engine applies.

        Args:
            engine (BachelierSwaptionEngine): The engine and its
                normal-volatility surface.
        """
    def calculate(self) -> None:
        r"""
        Force the valuation. Idempotent.

        Raises:
            ItofinError: If no engine is attached, no evaluation date is set,
                or the (settlement type, method) pair is inconsistent, which
                the core checks here rather than at construction.
        """
    def is_calculated(self) -> builtins.bool:
        r"""
        Return whether the cached results are currently valid.

        Returns:
            bool: True when the next accessor reads the cache.
        """
    def price(self, engine: pricingengines.BlackSwaptionEngine) -> builtins.float:
        r"""
        Attach the Black engine and return the NPV.

        set_black_engine followed by npv, in one call. Black is the primary
        because it is the standard swaption engine; the Jamshidian and
        Bachelier engines keep their own setters.

        Args:
            engine (BlackSwaptionEngine): The engine to install and price on.

        Returns:
            float: The swaption value.

        Raises:
            ItofinError: On anything that makes the valuation fail.
        """
    def results(self) -> results.Results:
        r"""
        Return a frozen snapshot of the valuation, calculating first.

        Returns:
            Results: A copy of the valuation results.

        Raises:
            ItofinError: On anything that makes the valuation fail.
        """
    def npv(self) -> builtins.float:
        r"""
        Return the swaption NPV under the attached engine.

        Returns:
            float: The present value.

        Raises:
            ItofinError: If no engine is attached or the (settlement type,
                method) pair is inconsistent.
        """

@typing.final
class VanillaOption:
    r"""
    A single-asset vanilla option: European by construction, American through american().

    Valuation is lazy: an accessor reprices only once an observed input - the
    attached engine, or the evaluation date on the Settings the option
    registered with - has notified it.
    """
    def __init__(self, option_type: OptionType, strike: builtins.float, expiry: time.Date, settings: itofin.Settings) -> None:
        r"""
        Build the European-exercise option, exercisable only at expiry.

        Args:
            option_type (OptionType): Whether the payoff is a call or a put.
            strike (float): The strike of the plain vanilla payoff.
            expiry (Date): The single date the option may be exercised on.
            settings (Settings): The explicit settings supplying the evaluation
                date the option prices against.
        """
    @classmethod
    def american(cls, option_type: OptionType, strike: builtins.float, earliest: time.Date, latest: time.Date, settings: itofin.Settings) -> VanillaOption:
        r"""
        Build the option exercisable at any time over [earliest, latest].

        The option pays on exercise rather than at expiry. This is the exercise
        the Monte Carlo American engine requires; the analytic European engine
        rejects it.

        Args:
            option_type (OptionType): Whether the payoff is a call or a put.
            strike (float): The strike of the plain vanilla payoff.
            earliest (Date): The first date the option may be exercised on.
            latest (Date): The last date the option may be exercised on.
            settings (Settings): The explicit settings supplying the evaluation
                date the option prices against.

        Returns:
            VanillaOption: The American-exercise option.

        Raises:
            ItofinError: If earliest is after latest.
        """
    def set_engine(self, process: processes.BlackScholesProcess) -> None:
        r"""
        Attach an analytic European engine built on process.

        Args:
            process (BlackScholesProcess): The process the engine prices on;
                the exact object this Python instance holds is threaded in.
        """
    def set_heston_engine(self, model: models.HestonModel, integration_order: builtins.int) -> None:
        r"""
        Attach an analytic Heston engine built on model.

        The analytic Heston engine fills only the value, so npv() works but the
        greeks raise on this path.

        Args:
            model (HestonModel): The calibrated Heston model to price under.
            integration_order (int): The order of the Gauss-Laguerre
                integration.

        Raises:
            ItofinError: If integration_order exceeds 192.
        """
    def set_mc_engine(self, engine: pricingengines.MCEuropeanEngine) -> None:
        r"""
        Attach the Monte Carlo European engine.

        Args:
            engine (MCEuropeanEngine): The engine, which already holds the
                process it prices on.
        """
    def set_mc_heston_engine(self, engine: pricingengines.MCEuropeanHestonEngine) -> None:
        r"""
        Attach the Monte Carlo Heston engine.

        Args:
            engine (MCEuropeanHestonEngine): The engine, which already holds
                the Heston process it prices on.
        """
    def set_mc_american_engine(self, engine: pricingengines.MCAmericanEngine) -> None:
        r"""
        Attach the Monte Carlo American engine.

        The option must have been built through american(): a European-exercise
        option raises ItofinError ("wrong exercise given") from npv().

        Args:
            engine (MCAmericanEngine): The engine, which already holds the
                process it prices on.
        """
    def calculate(self) -> None:
        r"""
        Force the valuation, so a later accessor reads a warm cache.

        Idempotent: the core short-circuits on a valid cache, and the option
        reprices only once an observed input notified it.

        Raises:
            ItofinError: If no engine is attached, no evaluation date is set,
                or the attached engine refuses the option.
        """
    def is_calculated(self) -> builtins.bool:
        r"""
        Return whether the cached results are currently valid.

        Returns:
            bool: True when the next accessor reads the cache rather than
                repricing.
        """
    def price(self, process: processes.BlackScholesProcess) -> builtins.float:
        r"""
        Attach an analytic European engine on process and return the NPV.

        The one-shot form of set_engine followed by npv. The other engines have
        their own one-shots: price_heston, price_mc, price_mc_heston and
        price_mc_american.

        Args:
            process (BlackScholesProcess): The process the engine prices on.

        Returns:
            float: The present value under the analytic European engine.

        Raises:
            ItofinError: If no evaluation date is set or the engine refuses the
                option.
        """
    def price_heston(self, model: models.HestonModel, integration_order: builtins.int) -> builtins.float:
        r"""
        Attach an analytic Heston engine on model and return the NPV.

        The one-shot form of set_heston_engine followed by npv. The greeks stay
        unavailable on this path.

        Args:
            model (HestonModel): The calibrated Heston model to price under.
            integration_order (int): The order of the Gauss-Laguerre
                integration.

        Returns:
            float: The present value under the analytic Heston engine.

        Raises:
            ItofinError: If integration_order exceeds 192, no evaluation date is
                set, or the engine refuses the option.
        """
    def price_mc(self, engine: pricingengines.MCEuropeanEngine) -> builtins.float:
        r"""
        Attach the Monte Carlo European engine and return the NPV.

        The one-shot form of set_mc_engine followed by npv.

        Args:
            engine (MCEuropeanEngine): The engine, which already holds the
                process it prices on.

        Returns:
            float: The present value under the Monte Carlo European engine.

        Raises:
            ItofinError: If no evaluation date is set or the engine refuses the
                option.
        """
    def price_mc_heston(self, engine: pricingengines.MCEuropeanHestonEngine) -> builtins.float:
        r"""
        Attach the Monte Carlo Heston engine and return the NPV.

        The one-shot form of set_mc_heston_engine followed by npv.

        Args:
            engine (MCEuropeanHestonEngine): The engine, which already holds
                the Heston process it prices on.

        Returns:
            float: The present value under the Monte Carlo Heston engine.

        Raises:
            ItofinError: If no evaluation date is set or the engine refuses the
                option.
        """
    def price_mc_american(self, engine: pricingengines.MCAmericanEngine) -> builtins.float:
        r"""
        Attach the Monte Carlo American engine and return the NPV.

        The one-shot form of set_mc_american_engine followed by npv. The option
        must have been built through american(): a European-exercise option
        raises ItofinError ("wrong exercise given").

        Args:
            engine (MCAmericanEngine): The engine, which already holds the
                process it prices on.

        Returns:
            float: The present value under the Monte Carlo American engine.

        Raises:
            ItofinError: If the option is not American-exercise, no evaluation
                date is set, or the engine refuses the option.
        """
    def results(self) -> results.Results:
        r"""
        Return a frozen snapshot of the valuation, calculating first.

        The snapshot does not track the option: once taken, an evaluation-date
        or engine change reprices the live accessors and leaves it alone.

        Returns:
            Results: A copy of the valuation results.

        Raises:
            ItofinError: On anything that makes the valuation fail.
        """
    def npv(self) -> builtins.float:
        r"""
        Return the present value.

        Returns:
            float: The option value under the attached engine.

        Raises:
            ItofinError: If no evaluation date or no engine is set.
        """
    def delta(self) -> builtins.float:
        r"""
        Return the option delta.

        Returns:
            float: The sensitivity to the underlying spot.

        Raises:
            ItofinError: If the attached engine does not provide it, which the
                analytic Heston engine does not.
        """
    def gamma(self) -> builtins.float:
        r"""
        Return the option gamma.

        Returns:
            float: The second-order sensitivity to the underlying spot.

        Raises:
            ItofinError: If the attached engine does not provide it.
        """
    def theta(self) -> builtins.float:
        r"""
        Return the option theta.

        Returns:
            float: The sensitivity to the passage of time.

        Raises:
            ItofinError: If the attached engine does not provide it.
        """
    def vega(self) -> builtins.float:
        r"""
        Return the option vega.

        Returns:
            float: The sensitivity to the volatility.

        Raises:
            ItofinError: If the attached engine does not provide it.
        """
    def rho(self) -> builtins.float:
        r"""
        Return the option rho.

        Returns:
            float: The sensitivity to the risk-free rate.

        Raises:
            ItofinError: If the attached engine does not provide it.
        """
    def dividend_rho(self) -> builtins.float:
        r"""
        Return the option dividend rho.

        Returns:
            float: The sensitivity to the dividend yield.

        Raises:
            ItofinError: If the attached engine does not provide it.
        """
    def error_estimate(self) -> builtins.float:
        r"""
        Return the standard error on the present value.

        Returns:
            float: The Monte Carlo standard error.

        Raises:
            ItofinError: On the engines that do not produce one, which is every
                analytic engine here.
        """
    def exercise_probability(self) -> builtins.float:
        r"""
        Return the fraction of simulated paths exercised before expiry.

        Returns:
            float: The exercise probability reported by the engine.

        Raises:
            ItofinError: On every engine that does not report it - only
                MCAmericanEngine does.
        """

@typing.final
class VanillaSwap:
    r"""
    A fixed-vs-Ibor interest-rate swap.

    Pricing needs an engine: call set_engine before fair_rate or npv.
    """
    def __init__(self, swap_type: SwapType, nominal: builtins.float, fixed_schedule: time.Schedule, fixed_rate: builtins.float, fixed_day_count: time.DayCounter, float_schedule: time.Schedule, ibor_index: indexes.IborIndex, spread: builtins.float, floating_day_count: time.DayCounter, settings: itofin.Settings) -> None:
        r"""
        Build the swap from both schedules spelled out.

        Args:
            swap_type (SwapType): Whether the fixed leg is paid or received.
            nominal (float): The notional both legs accrue on.
            fixed_schedule (Schedule): The fixed leg's payment schedule.
            fixed_rate (float): The rate the fixed leg accrues at.
            fixed_day_count (DayCounter): The day count of the fixed leg.
            float_schedule (Schedule): The floating leg's payment schedule.
            ibor_index (IborIndex): The index the floating leg fixes off.
            spread (float): The spread added to every floating fixing.
            floating_day_count (DayCounter): The day count of the floating leg.
            settings (Settings): The explicit settings supplying the evaluation
                date and the stored fixings.

        Raises:
            ItofinError: If the floating leg cannot be built, a degenerate leg
                being the usual cause.
        """
    def set_engine(self, curve: termstructures.YieldTermStructure, settings: itofin.Settings) -> None:
        r"""
        Attach a discounting engine over curve so the swap prices.

        The engine is built with the settings-driven flow defaults, leaving the
        settlement date, the NPV date and the settlement-date-flows flag unset.

        Args:
            curve (YieldTermStructure): The curve the flows discount on.
            settings (Settings): The settings the engine resolves its dates
                against.
        """
    def calculate(self) -> None:
        r"""
        Force the valuation. Idempotent.

        Raises:
            ItofinError: If no engine is attached, no evaluation date is set,
                or the attached engine refuses the swap.
        """
    def is_calculated(self) -> builtins.bool:
        r"""
        Return whether the cached results are currently valid.

        Returns:
            bool: True when the next accessor reads the cache.
        """
    def price(self, curve: termstructures.YieldTermStructure, settings: itofin.Settings) -> builtins.float:
        r"""
        Attach a discounting engine over curve and return the NPV.

        set_engine followed by npv, in one call, and it takes the same two
        arguments for the same reason.

        Args:
            curve (YieldTermStructure): The curve the flows discount on.
            settings (Settings): The settings the engine resolves its dates
                against.

        Returns:
            float: The swap value under the freshly built engine.

        Raises:
            ItofinError: On anything that makes the valuation fail.
        """
    def results(self) -> results.Results:
        r"""
        Return a frozen snapshot of the valuation, calculating first.

        Returns:
            Results: A copy of the valuation results.

        Raises:
            ItofinError: On anything that makes the valuation fail.
        """
    def fair_rate(self) -> builtins.float:
        r"""
        Return the fixed rate that zeroes the swap NPV.

        Returns:
            float: The fair fixed rate.

        Raises:
            ItofinError: If no engine is attached or the swap has expired.
        """
    def npv(self) -> builtins.float:
        r"""
        Return the swap NPV under the attached engine.

        Returns:
            float: The present value.

        Raises:
            ItofinError: If no engine is attached.
        """
    def nominal(self) -> builtins.float:
        r"""
        Return the notional both legs accrue on.

        Returns:
            float: The single nominal.

        Raises:
            ItofinError: If the legs carry per-coupon nominals, which leaves no
                single one to report.
        """
    def fixed_rate(self) -> builtins.float:
        r"""
        Return the fixed-leg rate.

        Returns:
            float: The rate the fixed leg accrues at.
        """

@typing.final
class YearOnYearInflationSwap:
    r"""
    A fixed leg against a leg of year-on-year inflation coupons, both paid over a schedule.

    SwapType names the fixed leg, so a Payer pays fixed and receives inflation -
    the opposite reading from ZeroCouponInflationSwap, where it names the
    inflation leg.

    The two schedules are independent inputs. The fixed leg takes its payment
    calendar from its own schedule while the year-on-year leg pays on
    payment_calendar; both adjust with payment_convention. spread is added to
    every forecast rate on the year-on-year leg.

    Pricing needs an engine: call set_engine first. Every priced accessor drives
    the calculation, so all of them mutate.
    """
    def __init__(self, swap_type: SwapType, nominal: builtins.float, fixed_schedule: time.Schedule, fixed_rate: builtins.float, fixed_day_count: time.DayCounter, yoy_schedule: time.Schedule, yoy_index: indexes.YoYInflationIndex, observation_lag: time.Period, interpolation: indexes.CpiInterpolationType, spread: builtins.float, yoy_day_count: time.DayCounter, payment_calendar: time.Calendar, payment_convention: time.BusinessDayConvention, settings: itofin.Settings) -> None:
        r"""
        Build the swap from its two schedules.

        Args:
            swap_type (SwapType): Which side the fixed leg is seen from; a
                Payer pays fixed and receives inflation.
            nominal (float): The notional both legs accrue on.
            fixed_schedule (Schedule): The fixed leg's payment schedule, which
                also supplies its payment calendar.
            fixed_rate (float): The rate the fixed leg accrues at.
            fixed_day_count (DayCounter): The day count of the fixed leg.
            yoy_schedule (Schedule): The year-on-year leg's schedule.
            yoy_index (YoYInflationIndex): The index the coupons fix off.
            observation_lag (Period): How far back each coupon's fixings are
                observed.
            interpolation (CpiInterpolationType): How the observed fixings are
                interpolated.
            spread (float): Added to every forecast rate on the year-on-year
                leg.
            yoy_day_count (DayCounter): The day count of the year-on-year leg.
            payment_calendar (Calendar): The calendar the year-on-year leg pays
                on.
            payment_convention (BusinessDayConvention): The roll both legs
                adjust their payment dates with.
            settings (Settings): The explicit settings supplying the evaluation
                date and the stored fixings.

        Raises:
            ItofinError: If either leg cannot be built, notably from an
                observation lag that leaves a coupon unbuildable.
        """
    def set_engine(self, engine: pricingengines.DiscountingSwapEngine) -> None:
        r"""
        Attach a discounting engine so the swap prices.

        Args:
            engine (DiscountingSwapEngine): The engine, which must resolve its
                dates against the same Settings object this swap was built
                with.
        """
    def calculate(self) -> None:
        r"""
        Force the valuation. Idempotent.

        Raises:
            ItofinError: If no engine is attached, no evaluation date is set,
                or the engine refuses the swap.
        """
    def is_calculated(self) -> builtins.bool:
        r"""
        Return whether the cached results are currently valid.

        Returns:
            bool: True when the next accessor reads the cache.
        """
    def price(self, engine: pricingengines.DiscountingSwapEngine) -> builtins.float:
        r"""
        Attach engine and return the NPV.

        Args:
            engine (DiscountingSwapEngine): The engine to install and price on.

        Returns:
            float: The swap value.

        Raises:
            ItofinError: On anything that makes the valuation fail.
        """
    def results(self) -> results.Results:
        r"""
        Return a frozen snapshot of the valuation, calculating first.

        Returns:
            Results: A copy of the valuation results.

        Raises:
            ItofinError: On anything that makes the valuation fail.
        """
    def npv(self) -> builtins.float:
        r"""
        Return the swap NPV under the attached engine.

        Returns:
            float: The present value.

        Raises:
            ItofinError: If no engine is attached, and if no curve is linked
                into the index, which leaves the coupons unforecastable.
        """
    def fair_rate(self) -> builtins.float:
        r"""
        Return the fixed rate that would price the swap at zero.

        Recovered from the NPV and the fixed leg's BPS, so it prices on demand
        and needs an engine.

        Returns:
            float: The fair fixed rate.

        Raises:
            ItofinError: On the same conditions npv reports.
        """
    def fair_spread(self) -> builtins.float:
        r"""
        Return the spread over the index that would price the swap at zero.

        Recovered off the year-on-year leg.

        Returns:
            float: The fair spread.

        Raises:
            ItofinError: On the same conditions fair_rate reports.
        """
    def fixed_leg_npv(self) -> builtins.float:
        r"""
        Return the fixed leg's NPV, priced on demand.

        Returns:
            float: The present value of the fixed leg.

        Raises:
            ItofinError: On the same conditions npv reports.
        """
    def yoy_leg_npv(self) -> builtins.float:
        r"""
        Return the year-on-year leg's NPV, priced on demand.

        Returns:
            float: The present value of the inflation leg.

        Raises:
            ItofinError: On the same conditions npv reports.
        """
    def fixed_rate(self) -> builtins.float:
        r"""
        Return the quoted fixed rate the swap was struck at.

        Returns:
            float: The fixed-leg rate.
        """
    def spread(self) -> builtins.float:
        r"""
        Return the spread the year-on-year coupons carry over the index.

        Returns:
            float: The quoted spread.
        """

@typing.final
class YoYInflationCapFloor:
    r"""
    A cap, floor or collar over a year-on-year inflation leg.

    Built either through MakeYoYInflationCapFloor, the standard market builder,
    or through the raw constructors below, which take the coupon vector
    YoYInflationLeg.coupons() hands back (#848). The raw route is the only one
    that reaches a collar: the builder carries a single strike.

    Unlike a nominal cap/floor this instrument keeps its first optionlet, so the
    strip spans its leg exactly and cap - floor is the year-on-year swap.

    Pricing needs an engine: call set_engine before npv.
    """
    @staticmethod
    def new(cap_floor_type: CapFloorType, coupons: typing.Sequence[cashflows.YoYInflationCoupon], cap_rates: typing.Sequence[builtins.float], floor_rates: typing.Sequence[builtins.float], settings: itofin.Settings) -> YoYInflationCapFloor:
        r"""
        Build an instrument of cap_floor_type over coupons, struck at both vectors.

        Each strike vector is padded to the leg length by repeating its last
        entry, so a single strike stands for every optionlet.

        Args:
            cap_floor_type (CapFloorType): Cap, Floor or Collar.
            coupons (list[YoYInflationCoupon]): The leg the optionlets sit on.
            cap_rates (list[float]): The cap strikes.
            floor_rates (list[float]): The floor strikes.
            settings (Settings): The explicit settings the instrument resolves
                its dates against.

        Returns:
            YoYInflationCapFloor: The built instrument.

        Raises:
            ItofinError: On an empty leg, and on a strike vector the type needs
                and did not get: a cap or a collar needs cap rates, a floor or
                a collar floor rates.
        """
    @staticmethod
    def cap(coupons: typing.Sequence[cashflows.YoYInflationCoupon], strikes: typing.Sequence[builtins.float], settings: itofin.Settings) -> YoYInflationCapFloor:
        r"""
        Build a cap over coupons struck at strikes.

        Args:
            coupons (list[YoYInflationCoupon]): The leg the optionlets sit on.
            strikes (list[float]): The cap strikes, padded as new() pads.
            settings (Settings): The explicit settings the instrument resolves
                its dates against.

        Returns:
            YoYInflationCapFloor: The cap over that leg.

        Raises:
            ItofinError: On the same conditions new() reports.
        """
    @staticmethod
    def floor(coupons: typing.Sequence[cashflows.YoYInflationCoupon], strikes: typing.Sequence[builtins.float], settings: itofin.Settings) -> YoYInflationCapFloor:
        r"""
        Build a floor over coupons struck at strikes.

        Args:
            coupons (list[YoYInflationCoupon]): The leg the optionlets sit on.
            strikes (list[float]): The floor strikes, padded as new() pads.
            settings (Settings): The explicit settings the instrument resolves
                its dates against.

        Returns:
            YoYInflationCapFloor: The floor over that leg.

        Raises:
            ItofinError: On the same conditions new() reports.
        """
    @staticmethod
    def collar(coupons: typing.Sequence[cashflows.YoYInflationCoupon], cap_rates: typing.Sequence[builtins.float], floor_rates: typing.Sequence[builtins.float], settings: itofin.Settings) -> YoYInflationCapFloor:
        r"""
        Build a collar: long the cap at cap_rates, short the floor at floor_rates.

        Args:
            coupons (list[YoYInflationCoupon]): The leg the optionlets sit on.
            cap_rates (list[float]): The cap strikes, padded as new() pads.
            floor_rates (list[float]): The floor strikes, padded the same way.
            settings (Settings): The explicit settings the instrument resolves
                its dates against.

        Returns:
            YoYInflationCapFloor: The collar over that leg.

        Raises:
            ItofinError: On the same conditions new() reports.
        """
    @staticmethod
    def with_strikes(cap_floor_type: CapFloorType, coupons: typing.Sequence[cashflows.YoYInflationCoupon], strikes: typing.Sequence[builtins.float], settings: itofin.Settings) -> YoYInflationCapFloor:
        r"""
        Build a cap or a floor from a single strike vector.

        Args:
            cap_floor_type (CapFloorType): Cap or Floor.
            coupons (list[YoYInflationCoupon]): The leg the optionlets sit on.
            strikes (list[float]): Cap rates for a Cap and floor rates for a
                Floor.
            settings (Settings): The explicit settings the instrument resolves
                its dates against.

        Returns:
            YoYInflationCapFloor: The built instrument.

        Raises:
            ItofinError: On an empty strikes, on a Collar - which needs two
                vectors, so collar() is its constructor - and on the same
                conditions new() reports.
        """
    def cap_rates(self) -> builtins.list[builtins.float]:
        r"""
        Return the cap strikes, one per coupon.

        Returns:
            list[float]: The cap strikes; empty on a floor.
        """
    def floor_rates(self) -> builtins.list[builtins.float]:
        r"""
        Return the floor strikes, one per coupon.

        Returns:
            list[float]: The floor strikes; empty on a cap.
        """
    def coupon_count(self) -> builtins.int:
        r"""
        Return the number of optionlets.

        Returns:
            int: One per year-on-year coupon on the leg.
        """
    def start_date(self) -> time.Date:
        r"""
        Return the leg's earliest accrual start.

        Returns:
            Date: The first accrual start date.

        Raises:
            ItofinError: On an empty leg, which the constructors already
                refuse.
        """
    def maturity_date(self) -> time.Date:
        r"""
        Return the leg's latest accrual end.

        Returns:
            Date: The last accrual end date.

        Raises:
            ItofinError: On the same conditions start_date reports.
        """
    def atm_rate(self, discount_curve: termstructures.YieldTermStructure) -> builtins.float:
        r"""
        Return the strike at which the leg reprices on discount_curve.

        The core takes the curve itself rather than a handle, so the link is
        resolved for the call.

        Args:
            discount_curve (YieldTermStructure): The curve the leg reprices on.

        Returns:
            float: The at-the-money rate.

        Raises:
            ItofinError: On an unlinked discount_curve, a curve with no
                reference date, and a leg with no basis-point sensitivity to
                solve over.
        """
    def set_engine(self, engine: pricingengines.YoYInflationCapFloorEngine) -> None:
        r"""
        Attach an engine, replacing whatever the factory installed.

        Args:
            engine (YoYInflationCapFloorEngine): The engine, which must resolve
                its dates against the same Settings object this cap/floor was
                built with: two different ones would price the leg and the
                optionlets on different dates with no error raised.
        """
    def calculate(self) -> None:
        r"""
        Force the valuation. Idempotent.

        Raises:
            ItofinError: If no engine is attached, no evaluation date is set,
                or the engine refuses the instrument.
        """
    def is_calculated(self) -> builtins.bool:
        r"""
        Return whether the cached results are currently valid.

        Returns:
            bool: True when the next accessor reads the cache.
        """
    def price(self, engine: pricingengines.YoYInflationCapFloorEngine) -> builtins.float:
        r"""
        Attach engine and return the NPV.

        Replaces whatever engine the factory installed.

        Args:
            engine (YoYInflationCapFloorEngine): The engine to install and
                price on.

        Returns:
            float: The cap/floor value.

        Raises:
            ItofinError: On anything that makes the valuation fail.
        """
    def results(self) -> results.Results:
        r"""
        Return a frozen snapshot of the valuation, calculating first.

        Returns:
            Results: A copy of the valuation results.

        Raises:
            ItofinError: On anything that makes the valuation fail.
        """
    def npv(self) -> builtins.float:
        r"""
        Return the cap/floor NPV under the attached engine.

        Returns:
            float: The present value.

        Raises:
            ItofinError: If no engine is attached, which the core reports as
                "null pricing engine", and on whatever the engine reports.
        """

@typing.final
class ZeroCouponInflationSwap:
    r"""
    One fixed flow against one inflation-indexed flow, both exchanged at maturity.

    fixed_rate is the K that at inception matches the inflation growth.
    SwapType names the inflation leg, so a Payer pays inflation and receives
    fixed.

    maturity is pre-adjustment: each leg's payment date is it rolled on that
    leg's calendar and convention, while the year fraction behind the fixed
    amount stays on the raw date. inflation_calendar and inflation_convention
    fall back to the fixed-leg ones when None.

    The core omits adjust_inf_obs_dates from its own signature, so there is
    nothing to expose here; the leg and cash-flow accessors are not surfaced
    either, there being no cash-flow facade.

    Pricing needs an engine: call set_engine() before npv(). fair_rate() is the
    exception, reading the indexed flow directly and pricing with no engine at
    all, though it does need the index linked to a curve.
    """
    def __init__(self, swap_type: SwapType, nominal: builtins.float, start_date: time.Date, maturity: time.Date, fixed_calendar: time.Calendar, fixed_convention: time.BusinessDayConvention, day_counter: time.DayCounter, fixed_rate: builtins.float, inflation_index: indexes.ZeroInflationIndex, observation_lag: time.Period, observation_interpolation: indexes.CpiInterpolationType, inflation_calendar: typing.Optional[time.Calendar], inflation_convention: typing.Optional[time.BusinessDayConvention], settings: itofin.Settings) -> None:
        r"""
        Build the swap from its two exchanged flows.

        Args:
            swap_type (SwapType): Which side the inflation leg is seen from; a
                Payer pays inflation and receives fixed.
            nominal (float): The notional both flows are quoted on.
            start_date (Date): The inception the index ratio is measured from.
            maturity (Date): The raw, pre-adjustment maturity.
            fixed_calendar (Calendar): The calendar the fixed payment rolls on.
            fixed_convention (BusinessDayConvention): The roll applied to the
                fixed payment date.
            day_counter (DayCounter): The day count behind the fixed amount,
                which stays on the raw maturity.
            fixed_rate (float): The K that at inception matches the inflation
                growth.
            inflation_index (ZeroInflationIndex): The index the indexed flow
                observes.
            observation_lag (Period): How far back the maturity fixing is
                observed.
            observation_interpolation (CpiInterpolationType): How the observed
                fixing is interpolated.
            inflation_calendar (Calendar | None): The calendar the inflation
                payment rolls on; None falls back to fixed_calendar.
            inflation_convention (BusinessDayConvention | None): The roll
                applied to the inflation payment date; None falls back to
                fixed_convention.
            settings (Settings): The explicit settings supplying the evaluation
                date and the stored fixings.

        Raises:
            ItofinError: If the observation lag is too short for the index to
                observe fixings that exist, which under Linear interpolation
                costs a further publication period.
        """
    def set_engine(self, engine: pricingengines.DiscountingSwapEngine) -> None:
        r"""
        Attach a discounting engine so the swap prices.

        Args:
            engine (DiscountingSwapEngine): The engine, which must resolve its
                dates against the same Settings object as this swap.
        """
    def calculate(self) -> None:
        r"""
        Force the valuation. Idempotent.

        Raises:
            ItofinError: If no engine is attached, no evaluation date is set,
                or the engine refuses the swap.
        """
    def is_calculated(self) -> builtins.bool:
        r"""
        Return whether the cached results are currently valid.

        Returns:
            bool: True when the next accessor reads the cache.
        """
    def price(self, engine: pricingengines.DiscountingSwapEngine) -> builtins.float:
        r"""
        Attach engine and return the NPV.

        Args:
            engine (DiscountingSwapEngine): The engine to install and price on.

        Returns:
            float: The swap value.

        Raises:
            ItofinError: On anything that makes the valuation fail.
        """
    def results(self) -> results.Results:
        r"""
        Return a frozen snapshot of the valuation, calculating first.

        Returns:
            Results: A copy of the valuation results.

        Raises:
            ItofinError: On anything that makes the valuation fail.
        """
    def npv(self) -> builtins.float:
        r"""
        Return the swap NPV under the attached engine.

        Returns:
            float: The present value.

        Raises:
            ItofinError: If no engine is attached, and if no curve is linked
                into the index, which leaves the indexed flow unforecastable.
        """
    def fair_rate(self) -> builtins.float:
        r"""
        Return the index ratio de-compounded over the swap's own year fraction.

        Needs no engine - it reads the indexed flow rather than any priced
        result.

        Returns:
            float: The rate that would price the swap at zero.

        Raises:
            ItofinError: If no curve is linked into the index, the flow's
                amount being a forecast off the inflation curve.
        """
    def fixed_leg_npv(self) -> builtins.float:
        r"""
        Return the fixed leg's NPV, priced on demand.

        Returns:
            float: The present value of the fixed flow.

        Raises:
            ItofinError: On the same conditions npv reports.
        """
    def inflation_leg_npv(self) -> builtins.float:
        r"""
        Return the inflation leg's NPV, priced on demand.

        Returns:
            float: The present value of the indexed flow.

        Raises:
            ItofinError: On the same conditions npv reports.
        """
    def fixed_leg_bps(self) -> builtins.float:
        r"""
        Return the fixed leg's sensitivity to a basis point on the quoted rate.

        Computed in closed form rather than read off the engine, whose own leg
        BPS is zero for a non-coupon flow.

        Returns:
            float: The basis-point value of the fixed flow.

        Raises:
            ItofinError: On the same conditions npv reports, the calculation
                needing the engine's discount factor at the fixed leg's end
                date.
        """
    def maturity_date(self) -> time.Date:
        r"""
        Return the contract maturity, raw and pre-adjustment.

        Returns:
            Date: The maturity, which is not either leg's payment date.
        """
    def obs_date(self) -> time.Date:
        r"""
        Return the date the maturity fixing is observed at.

        Returns:
            Date: The maturity less the observation lag, unsnapped.
        """
    def inflation_fixing_date(self) -> time.Date:
        r"""
        Return the observation date, read off the indexed flow.

        Both names are kept because both exist in the core, and the oracle
        asserts they coincide.

        Returns:
            Date: The same date as obs_date.
        """

@typing.final
class CapFloorType:
    r"""
    Whether the instrument caps, floors or collars its floating leg.

    Collar reaches an instrument only through a raw coupon-vector constructor:
    CapFloor.collar here, or the YoYInflationCapFloor ones on the inflation
    side. MakeCapFloor refuses it, so CapFloor(...) does not accept it.
    """
    Cap: typing.ClassVar[CapFloorType]
    Floor: typing.ClassVar[CapFloorType]
    Collar: typing.ClassVar[CapFloorType]
    def __new__(cls, _unconstructible: typing.NoReturn) -> CapFloorType: ...
    def __int__(self) -> builtins.int: ...
    __hash__: typing.ClassVar[None]  # type: ignore[assignment]

@typing.final
class OptionType:
    r"""
    The call/put flag.

    A fieldless enum mirroring the core option type; the signed discriminant
    convention behind the two variants stays in the core.
    """
    Call: typing.ClassVar[OptionType]
    Put: typing.ClassVar[OptionType]
    def __new__(cls, _unconstructible: typing.NoReturn) -> OptionType: ...
    def __int__(self) -> builtins.int: ...
    __hash__: typing.ClassVar[None]  # type: ignore[assignment]

@typing.final
class Position:
    r"""
    The side taken in a contract.

    A fieldless enum; Long is an FRA purchase (a future long loan, short
    deposit), Short an FRA sale. The signed settlement multiplier the two
    variants stand for stays in the core.
    """
    Long: typing.ClassVar[Position]
    Short: typing.ClassVar[Position]
    def __new__(cls, _unconstructible: typing.NoReturn) -> Position: ...
    def __int__(self) -> builtins.int: ...
    __hash__: typing.ClassVar[None]  # type: ignore[assignment]

@typing.final
class PricingModel:
    r"""
    The model a quoted contract is inverted under by
    CreditDefaultSwap.implied_hazard_rate: Midpoint is not ISDA conform, Isda
    carries the three fidelity flags the core fixes at that call site.
    """
    Midpoint: typing.ClassVar[PricingModel]
    Isda: typing.ClassVar[PricingModel]
    def __new__(cls, _unconstructible: typing.NoReturn) -> PricingModel: ...
    def __int__(self) -> builtins.int: ...
    __hash__: typing.ClassVar[None]  # type: ignore[assignment]

@typing.final
class ProtectionSide:
    r"""
    Which leg of a default-protection contract a party holds: the buyer pays
    the premium leg and receives the default payment, the seller the reverse.
    """
    Buyer: typing.ClassVar[ProtectionSide]
    Seller: typing.ClassVar[ProtectionSide]
    def __new__(cls, _unconstructible: typing.NoReturn) -> ProtectionSide: ...
    def __int__(self) -> builtins.int: ...
    __hash__: typing.ClassVar[None]  # type: ignore[assignment]

@typing.final
class SettlementMethod:
    r"""
    The settlement mechanics under a settlement type.

    Physical pairs with PhysicalOTC or PhysicalCleared, cash with
    CollateralizedCashPrice or ParYieldCurve. The consistency check runs at
    pricing time, not construction, so a mismatched pair only surfaces from
    npv().
    """
    PhysicalOTC: typing.ClassVar[SettlementMethod]
    PhysicalCleared: typing.ClassVar[SettlementMethod]
    CollateralizedCashPrice: typing.ClassVar[SettlementMethod]
    ParYieldCurve: typing.ClassVar[SettlementMethod]
    def __new__(cls, _unconstructible: typing.NoReturn) -> SettlementMethod: ...
    def __int__(self) -> builtins.int: ...
    __hash__: typing.ClassVar[None]  # type: ignore[assignment]

@typing.final
class SettlementType:
    r"""
    How a swaption settles on exercise.
    """
    Physical: typing.ClassVar[SettlementType]
    Cash: typing.ClassVar[SettlementType]
    def __new__(cls, _unconstructible: typing.NoReturn) -> SettlementType: ...
    def __int__(self) -> builtins.int: ...
    __hash__: typing.ClassVar[None]  # type: ignore[assignment]

@typing.final
class SwapType:
    r"""
    Which side of the named leg the swap is seen from.

    A fieldless enum; the signed leg multiplier the two variants stand for
    stays in the core.
    """
    Payer: typing.ClassVar[SwapType]
    Receiver: typing.ClassVar[SwapType]
    def __new__(cls, _unconstructible: typing.NoReturn) -> SwapType: ...
    def __int__(self) -> builtins.int: ...
    __hash__: typing.ClassVar[None]  # type: ignore[assignment]
