# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from itofin import time
import numpy
import numpy.typing
import typing
__all__ = [
    "BollingerBands",
    "ChartSeries",
    "DatedIntervalPrice",
    "Garch11FitResult",
    "Garch11Result",
    "Kd",
    "KeltnerChannels",
    "Macd",
    "OhlcOvernightEstimates",
    "OhlcPointEstimates",
    "VolumeBars",
    "atr",
    "bollinger_bands",
    "constant_volatility",
    "ema",
    "garch11_filter",
    "garch11_fit",
    "garch11_forecast",
    "interval_prices",
    "kd",
    "keltner_channels",
    "macd",
    "obv",
    "ohlc_overnight_volatility",
    "ohlc_overnight_volatility_constant_fraction",
    "ohlc_point_volatility",
    "ohlc_point_volatility_constant_fraction",
    "rsi",
    "simple_local_volatility",
    "simple_local_volatility_constant_fraction",
    "sma",
    "true_range",
    "volume_bars",
    "vwap",
]

@typing.final
class BollingerBands:
    r"""
    Bollinger middle, upper, and lower bands aligned with input closes.
    """
    @property
    def middle(self) -> ChartSeries:
        r"""
        Rolling arithmetic mean.
        """
    @property
    def upper(self) -> ChartSeries:
        r"""
        Middle plus population standard deviation times the multiplier.
        """
    @property
    def lower(self) -> ChartSeries:
        r"""
        Middle minus population standard deviation times the multiplier.
        """

@typing.final
class ChartSeries:
    r"""
    Values aligned with input bars. Entries before `first_valid` are warmup slots.
    """
    @property
    def values(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        A float64 copy of all bars; warmup slots contain zero placeholders.
        """
    @property
    def first_valid(self) -> builtins.int:
        r"""
        Index of the first usable result, or the series length if none is usable.
        """
    def to_list(self) -> builtins.list[typing.Optional[builtins.float]]:
        r"""
        Copy values with `None` in warmup slots for JSON or chart libraries.
        """

@typing.final
class DatedIntervalPrice:
    r"""
    One validated OHLC bar and its calendar date.
    """
    @property
    def date(self) -> time.Date:
        r"""
        Calendar date of this bar.
        """
    @property
    def open(self) -> builtins.float:
        r"""
        Opening price.
        """
    @property
    def high(self) -> builtins.float:
        r"""
        Highest price.
        """
    @property
    def low(self) -> builtins.float:
        r"""
        Lowest price.
        """
    @property
    def close(self) -> builtins.float:
        r"""
        Closing price.
        """

@typing.final
class Garch11FitResult:
    r"""
    Fitted stationary GARCH(1,1) parameters and one-step variance forecast.
    """
    @property
    def alpha(self) -> builtins.float:
        r"""
        Fitted response to the preceding squared return.
        """
    @property
    def beta(self) -> builtins.float:
        r"""
        Fitted persistence of conditional variance.
        """
    @property
    def omega(self) -> builtins.float:
        r"""
        Fitted variance intercept.
        """
    @property
    def log_likelihood(self) -> builtins.float:
        r"""
        Gaussian log likelihood per return, excluding the constant term.
        """
    @property
    def next_variance(self) -> builtins.float:
        r"""
        Conditional variance forecast following the final return.
        """

@typing.final
class Garch11Result:
    r"""
    Conditional volatility aligned with returns and one-step variance forecast.
    """
    @property
    def conditional_volatility(self) -> ChartSeries:
        r"""
        Per-return conditional standard deviation in the return input's units.
        """
    @property
    def next_variance(self) -> builtins.float:
        r"""
        Conditional variance forecast following the final return.
        """

@typing.final
class Kd:
    r"""
    Taiwan stochastic oscillator lines aligned with input bars.
    """
    @property
    def rsv(self) -> ChartSeries:
        r"""
        Raw stochastic value, with a flat range set to 50.
        """
    @property
    def k(self) -> ChartSeries:
        r"""
        Smoothed K line, seeded at 50.
        """
    @property
    def d(self) -> ChartSeries:
        r"""
        Smoothed D line, seeded at 50.
        """

@typing.final
class KeltnerChannels:
    r"""
    Modern EMA-close center and Wilder-ATR envelopes, with shared warmup.
    """
    @property
    def center(self) -> ChartSeries:
        r"""
        EMA of closes, preserving the existing arithmetic seed.
        """
    @property
    def upper(self) -> ChartSeries:
        r"""
        Center plus the multiplier times Wilder ATR.
        """
    @property
    def lower(self) -> ChartSeries:
        r"""
        Center minus the multiplier times Wilder ATR.
        """

@typing.final
class Macd:
    r"""
    MACD line, signal, and histogram aligned with input closes.
    """
    @property
    def line(self) -> ChartSeries:
        r"""
        Difference between SMA-seeded fast and slow EMAs.
        """
    @property
    def signal(self) -> ChartSeries:
        r"""
        SMA-seeded EMA of valid MACD line values.
        """
    @property
    def histogram(self) -> ChartSeries:
        r"""
        Line minus signal.
        """

@typing.final
class OhlcOvernightEstimates:
    r"""
    Annualized overnight estimates aligned with the input OHLC bars.
    """
    @property
    def garman_klass_sigma1(self) -> ChartSeries:
        r"""
        Garman-Klass Sigma1 estimate using the preceding close.
        """
    @property
    def garman_klass_sigma3(self) -> ChartSeries:
        r"""
        Garman-Klass Sigma3 estimate using the preceding close.
        """
    @property
    def garman_klass_sigma6(self) -> ChartSeries:
        r"""
        Garman-Klass Sigma6 estimate using the preceding close.
        """

@typing.final
class OhlcPointEstimates:
    r"""
    Annualized volatility estimates aligned with the input OHLC bars.
    """
    @property
    def simple_sigma(self) -> ChartSeries:
        r"""
        Simple open-to-close estimate.
        """
    @property
    def parkinson_sigma(self) -> ChartSeries:
        r"""
        Parkinson high-low estimate.
        """
    @property
    def garman_klass_sigma4(self) -> ChartSeries:
        r"""
        Four-price Garman-Klass estimate.
        """
    @property
    def garman_klass_sigma5(self) -> ChartSeries:
        r"""
        Garman-Klass Sigma5 estimate.
        """

@typing.final
class VolumeBars:
    r"""
    Raw volume and the per-bar direction relative to the open.
    """
    @property
    def volume(self) -> ChartSeries:
        r"""
        Raw nonnegative volume, aligned with input bars.
        """
    @property
    def direction(self) -> numpy.typing.NDArray[numpy.int8]:
        r"""
        Per-bar direction: -1 for down, 0 for flat, 1 for up.
        """

def atr(high: typing.Sequence[builtins.float], low: typing.Sequence[builtins.float], close: typing.Sequence[builtins.float], period: builtins.int = 14) -> ChartSeries:
    r"""
    Wilder ATR with an arithmetic seed over the first period true ranges.
    Bar zero contributes high-low; first-valid is period-1, capped at length.
    Default period is 14; period one returns exactly the true-range series.
    """

def bollinger_bands(close: typing.Sequence[builtins.float], period: builtins.int = 20, multiplier: builtins.float = 2.0) -> BollingerBands:
    r"""
    Bollinger bands using a population standard deviation over each window.
    """

def constant_volatility(input: ChartSeries, window: builtins.int) -> ChartSeries:
    r"""
    Rolling volatility from preceding valid local values, excluding the current bar.
    """

def ema(close: typing.Sequence[builtins.float], period: builtins.int) -> ChartSeries:
    r"""
    Exponential moving average seeded by the first `period`-bar SMA.
    """

def garch11_filter(returns: typing.Sequence[builtins.float], alpha: builtins.float, beta: builtins.float, long_run_variance: builtins.float) -> Garch11Result:
    r"""
    Filter returns with fixed GARCH(1,1) parameters and long-run variance.
    """

def garch11_fit(returns: typing.Sequence[builtins.float]) -> Garch11FitResult:
    r"""
    Fit stationary GARCH(1,1) parameters to observed returns.
    """

def garch11_forecast(last_return: builtins.float, current_variance: builtins.float, alpha: builtins.float, beta: builtins.float, long_run_variance: builtins.float) -> builtins.float:
    r"""
    Forecast the next variance from the last return and current variance.
    """

def interval_prices(dates: typing.Sequence[time.Date], open: typing.Sequence[builtins.float], high: typing.Sequence[builtins.float], low: typing.Sequence[builtins.float], close: typing.Sequence[builtins.float]) -> builtins.list[DatedIntervalPrice]:
    r"""
    Build sorted dated OHLC bars; duplicate dates retain their last input bar.
    """

def kd(high: typing.Sequence[builtins.float], low: typing.Sequence[builtins.float], close: typing.Sequence[builtins.float], period: builtins.int = 9, k_smooth: builtins.int = 3, d_smooth: builtins.int = 3) -> Kd:
    r"""
    Taiwan KD with RSV and recursive K/D smoothing seeded at 50.
    """

def keltner_channels(high: typing.Sequence[builtins.float], low: typing.Sequence[builtins.float], close: typing.Sequence[builtins.float], center_period: builtins.int = 20, atr_period: builtins.int = 10, multiplier: builtins.float = 2.0) -> KeltnerChannels:
    r"""
    Modern Keltner channels with EMA(close) center and Wilder ATR envelopes.
    All three series share the later warmup index. Defaults are EMA 20,
    ATR 10 and multiplier 2; this differs from standalone ATR's default 14.
    """

def macd(close: typing.Sequence[builtins.float], fast_period: builtins.int = 12, slow_period: builtins.int = 26, signal_period: builtins.int = 9) -> Macd:
    r"""
    MACD with SMA-seeded fast, slow, and signal exponential averages.
    """

def obv(close: typing.Sequence[builtins.float], volume: typing.Sequence[builtins.float]) -> ChartSeries:
    r"""
    Zero-seeded OBV; rises add volume, falls subtract it, equal closes preserve it.
    The initial volume is validated but does not contribute to the zero seed.
    """

def ohlc_overnight_volatility(open: typing.Sequence[builtins.float], high: typing.Sequence[builtins.float], low: typing.Sequence[builtins.float], close: typing.Sequence[builtins.float], year_fractions: typing.Sequence[builtins.float], overnight_fraction: builtins.float) -> OhlcOvernightEstimates:
    r"""
    Estimate three annualized overnight series using each bar's year fraction.
    """

def ohlc_overnight_volatility_constant_fraction(open: typing.Sequence[builtins.float], high: typing.Sequence[builtins.float], low: typing.Sequence[builtins.float], close: typing.Sequence[builtins.float], year_fraction: builtins.float, overnight_fraction: builtins.float) -> OhlcOvernightEstimates:
    r"""
    Estimate three annualized overnight series with one year fraction per interval.
    """

def ohlc_point_volatility(open: typing.Sequence[builtins.float], high: typing.Sequence[builtins.float], low: typing.Sequence[builtins.float], close: typing.Sequence[builtins.float], year_fractions: typing.Sequence[builtins.float]) -> OhlcPointEstimates:
    r"""
    Estimate four annualized volatility series using each bar's year fraction.
    """

def ohlc_point_volatility_constant_fraction(open: typing.Sequence[builtins.float], high: typing.Sequence[builtins.float], low: typing.Sequence[builtins.float], close: typing.Sequence[builtins.float], year_fraction: builtins.float) -> OhlcPointEstimates:
    r"""
    Estimate four annualized volatility series with one year fraction per bar.
    """

def rsi(close: typing.Sequence[builtins.float], period: builtins.int = 14) -> ChartSeries:
    r"""
    Wilder RSI, seeded after `period` closing-price changes.
    """

def simple_local_volatility(close: typing.Sequence[builtins.float], year_fractions: typing.Sequence[builtins.float]) -> ChartSeries:
    r"""
    Absolute log returns annualized by each bar's year fraction.
    """

def simple_local_volatility_constant_fraction(close: typing.Sequence[builtins.float], year_fraction: builtins.float) -> ChartSeries:
    r"""
    Absolute log returns annualized by one year fraction for every bar.
    """

def sma(close: typing.Sequence[builtins.float], period: builtins.int) -> ChartSeries:
    r"""
    Simple moving average, seeded after `period` closing prices.
    """

def true_range(high: typing.Sequence[builtins.float], low: typing.Sequence[builtins.float], close: typing.Sequence[builtins.float]) -> ChartSeries:
    r"""
    Gap-aware true range, with high-low used for the first bar.
    Finite ordered HLC inputs and finite differences are required.
    """

def volume_bars(open: typing.Sequence[builtins.float], high: typing.Sequence[builtins.float], low: typing.Sequence[builtins.float], close: typing.Sequence[builtins.float], volume: typing.Sequence[builtins.float]) -> VolumeBars:
    r"""
    Validate OHLCV bars and return raw volume with close-versus-open direction.
    """

def vwap(price: typing.Sequence[builtins.float], volume: typing.Sequence[builtins.float]) -> ChartSeries:
    r"""
    Cumulative VWAP of supplied prices; a separate call starts a new session.
    Zero-volume prefixes are missing; later zero volume carries the last value.
    """
