# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "BusinessDayConvention",
    "Calendar",
    "Date",
    "DateGeneration",
    "DayCounter",
    "Frequency",
    "Period",
    "Schedule",
    "is_imm_date",
    "next_imm_date",
]

@typing.final
class Calendar:
    r"""
    A business-day calendar.
    """
    @property
    def name(self) -> builtins.str:
        r"""
        The calendar's name, as the core reports it.
        """
    @staticmethod
    def target() -> Calendar:
        r"""
        The TARGET calendar.

        Returns:
            Calendar: The TARGET business-day calendar.
        """
    @staticmethod
    def null_calendar() -> Calendar:
        r"""
        The calendar holding no holidays at all.

        Returns:
            Calendar: The null calendar, on which every day is a business day.
        """
    @staticmethod
    def weekends_only() -> Calendar:
        r"""
        The weekends-only calendar: Saturdays and Sundays are holidays and no
        other day is. The calendar the ISDA CDS conventions roll on.

        It is not substitutable by the null calendar, which holds no holidays at
        all, nor by a national calendar, which adds public holidays.

        Returns:
            Calendar: The weekends-only calendar.
        """
    @staticmethod
    def botswana() -> Calendar:
        r"""
        The Botswanan calendar.

        Returns:
            Calendar: The Botswanan calendar.
        """
    @staticmethod
    def denmark() -> Calendar:
        r"""
        The Danish calendar.

        Returns:
            Calendar: The Danish calendar.
        """
    @staticmethod
    def finland() -> Calendar:
        r"""
        The Finnish calendar.

        Returns:
            Calendar: The Finnish calendar.
        """
    @staticmethod
    def hungary() -> Calendar:
        r"""
        The Hungarian calendar.

        Returns:
            Calendar: The Hungarian calendar.
        """
    @staticmethod
    def japan() -> Calendar:
        r"""
        The Japanese calendar.

        Returns:
            Calendar: The Japanese calendar.
        """
    @staticmethod
    def norway() -> Calendar:
        r"""
        The Norwegian calendar.

        Returns:
            Calendar: The Norwegian calendar.
        """
    @staticmethod
    def south_africa() -> Calendar:
        r"""
        The South African calendar.

        Returns:
            Calendar: The South African calendar.
        """
    @staticmethod
    def sweden() -> Calendar:
        r"""
        The Swedish calendar.

        Returns:
            Calendar: The Swedish calendar.
        """
    @staticmethod
    def switzerland() -> Calendar:
        r"""
        The Swiss calendar.

        Returns:
            Calendar: The Swiss calendar.
        """
    @staticmethod
    def thailand() -> Calendar:
        r"""
        The Thai calendar.

        Returns:
            Calendar: The Thai calendar.
        """
    @staticmethod
    def turkey() -> Calendar:
        r"""
        The Turkish calendar.

        Returns:
            Calendar: The Turkish calendar.
        """
    @staticmethod
    def argentina(market: builtins.str = 'Merval') -> Calendar:
        r"""
        The Argentine calendar.

        Args:
            market (str): "Merval", the only market; matched ignoring case.

        Returns:
            Calendar: The Argentine calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def australia(market: builtins.str = 'Settlement') -> Calendar:
        r"""
        The Australian calendar.

        Args:
            market (str): One of "Settlement", "ASX"; matched ignoring case.

        Returns:
            Calendar: The Australian calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def austria(market: builtins.str = 'Settlement') -> Calendar:
        r"""
        The Austrian calendar.

        Args:
            market (str): One of "Settlement", "Exchange"; matched ignoring case.

        Returns:
            Calendar: The Austrian calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def brazil(market: builtins.str = 'Settlement') -> Calendar:
        r"""
        The Brazilian calendar.

        Args:
            market (str): One of "Settlement", "Exchange"; matched ignoring case.

        Returns:
            Calendar: The Brazilian calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def canada(market: builtins.str = 'Settlement') -> Calendar:
        r"""
        The Canadian calendar.

        Args:
            market (str): One of "Settlement", "TSX"; matched ignoring case.

        Returns:
            Calendar: The Canadian calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def chile(market: builtins.str = 'SSE') -> Calendar:
        r"""
        The Chilean calendar.

        Args:
            market (str): "SSE", the only market; matched ignoring case.

        Returns:
            Calendar: The Chilean calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def china(market: builtins.str = 'SSE') -> Calendar:
        r"""
        The Chinese calendar.

        Args:
            market (str): One of "SSE", "IB"; matched ignoring case.

        Returns:
            Calendar: The Chinese calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def croatia(market: builtins.str = 'ZSE') -> Calendar:
        r"""
        The Croatian calendar.

        Args:
            market (str): "ZSE", the only market; matched ignoring case.

        Returns:
            Calendar: The Croatian calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def czech_republic(market: builtins.str = 'PSE') -> Calendar:
        r"""
        The Czech calendar.

        Args:
            market (str): "PSE", the only market; matched ignoring case.

        Returns:
            Calendar: The Czech calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def france(market: builtins.str = 'Settlement') -> Calendar:
        r"""
        The French calendar.

        Args:
            market (str): One of "Settlement", "Exchange"; matched ignoring case.

        Returns:
            Calendar: The French calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def germany(market: builtins.str = 'Settlement') -> Calendar:
        r"""
        The German calendar.

        Args:
            market (str): One of "Settlement", "FrankfurtStockExchange", "Xetra", "Eurex", "Euwax"; matched ignoring case.

        Returns:
            Calendar: The German calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def hong_kong(market: builtins.str = 'HKEx') -> Calendar:
        r"""
        The Hong Kong calendar.

        Args:
            market (str): "HKEx", the only market; matched ignoring case.

        Returns:
            Calendar: The Hong Kong calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def iceland(market: builtins.str = 'ICEX') -> Calendar:
        r"""
        The Icelandic calendar.

        Args:
            market (str): "ICEX", the only market; matched ignoring case.

        Returns:
            Calendar: The Icelandic calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def india(market: builtins.str = 'NSE') -> Calendar:
        r"""
        The Indian calendar.

        Args:
            market (str): "NSE", the only market; matched ignoring case.

        Returns:
            Calendar: The Indian calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def indonesia(market: builtins.str = 'BEJ') -> Calendar:
        r"""
        The Indonesian calendar.

        Its public holidays are tabulated through 2014 only, as in QuantLib;
        every query on this calendar raises ItofinError for a later date
        rather than silently omitting holidays.

        Args:
            market (str): One of "BEJ", "JSX", "IDX"; matched ignoring case.

        Returns:
            Calendar: The Indonesian calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def israel(market: builtins.str = 'Settlement') -> Calendar:
        r"""
        The Israeli calendar.

        Args:
            market (str): One of "Settlement", "TASE", "SHIR", "Telbor"; matched ignoring case.

        Returns:
            Calendar: The Israeli calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def italy(market: builtins.str = 'Settlement') -> Calendar:
        r"""
        The Italian calendar.

        Args:
            market (str): One of "Settlement", "Exchange"; matched ignoring case.

        Returns:
            Calendar: The Italian calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def malta(market: builtins.str = 'MSE') -> Calendar:
        r"""
        The Maltese calendar.

        Args:
            market (str): "MSE", the only market; matched ignoring case.

        Returns:
            Calendar: The Maltese calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def mexico(market: builtins.str = 'BMV') -> Calendar:
        r"""
        The Mexican calendar.

        Args:
            market (str): "BMV", the only market; matched ignoring case.

        Returns:
            Calendar: The Mexican calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def montenegro(market: builtins.str = 'MNSE') -> Calendar:
        r"""
        The Montenegrin calendar.

        Args:
            market (str): "MNSE", the only market; matched ignoring case.

        Returns:
            Calendar: The Montenegrin calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def new_zealand(market: builtins.str = 'Wellington') -> Calendar:
        r"""
        The New Zealand calendar.

        Args:
            market (str): One of "Wellington", "Auckland"; matched ignoring case.

        Returns:
            Calendar: The New Zealand calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def north_macedonia(market: builtins.str = 'MSE') -> Calendar:
        r"""
        The North Macedonian calendar.

        Args:
            market (str): "MSE", the only market; matched ignoring case.

        Returns:
            Calendar: The North Macedonian calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def poland(market: builtins.str = 'Settlement') -> Calendar:
        r"""
        The Polish calendar.

        Args:
            market (str): One of "Settlement", "WSE"; matched ignoring case.

        Returns:
            Calendar: The Polish calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def romania(market: builtins.str = 'Public') -> Calendar:
        r"""
        The Romanian calendar.

        Args:
            market (str): One of "Public", "BVB"; matched ignoring case.

        Returns:
            Calendar: The Romanian calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def russia(market: builtins.str = 'Settlement') -> Calendar:
        r"""
        The Russian calendar.

        Args:
            market (str): One of "Settlement", "MOEX"; matched ignoring case.

        Returns:
            Calendar: The Russian calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def saudi_arabia(market: builtins.str = 'Tadawul') -> Calendar:
        r"""
        The Saudi Arabian calendar.

        Its Eid holidays are tabulated through 2022 only, as in QuantLib;
        every query on this calendar raises ItofinError for a later date
        rather than silently omitting holidays.

        Args:
            market (str): "Tadawul", the only market; matched ignoring case.

        Returns:
            Calendar: The Saudi Arabian calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def serbia(market: builtins.str = 'BSE') -> Calendar:
        r"""
        The Serbian calendar.

        Args:
            market (str): "BSE", the only market; matched ignoring case.

        Returns:
            Calendar: The Serbian calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def singapore(market: builtins.str = 'SGX') -> Calendar:
        r"""
        The Singapore calendar.

        Args:
            market (str): "SGX", the only market; matched ignoring case.

        Returns:
            Calendar: The Singapore calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def slovakia(market: builtins.str = 'BSSE') -> Calendar:
        r"""
        The Slovak calendar.

        Args:
            market (str): "BSSE", the only market; matched ignoring case.

        Returns:
            Calendar: The Slovak calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def slovenia(market: builtins.str = 'LSE') -> Calendar:
        r"""
        The Slovenian calendar.

        Args:
            market (str): "LSE", the only market; matched ignoring case.

        Returns:
            Calendar: The Slovenian calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def south_korea(market: builtins.str = 'Settlement') -> Calendar:
        r"""
        The South Korean calendar.

        Args:
            market (str): One of "Settlement", "KRX"; matched ignoring case.

        Returns:
            Calendar: The South Korean calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def taiwan(market: builtins.str = 'TSEC') -> Calendar:
        r"""
        The Taiwanese calendar.

        Args:
            market (str): "TSEC", the only market; matched ignoring case.

        Returns:
            Calendar: The Taiwanese calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def ukraine(market: builtins.str = 'USE') -> Calendar:
        r"""
        The Ukrainian calendar.

        Args:
            market (str): "USE", the only market; matched ignoring case.

        Returns:
            Calendar: The Ukrainian calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def united_kingdom(market: builtins.str = 'Settlement') -> Calendar:
        r"""
        The UK calendar.

        Args:
            market (str): One of "Settlement", "Exchange", "Metals"; matched ignoring case.

        Returns:
            Calendar: The UK calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def united_states(market: builtins.str = 'Settlement') -> Calendar:
        r"""
        The US calendar.

        Args:
            market (str): One of "Settlement", "NYSE", "GovernmentBond", "NERC", "LiborImpact", "FederalReserve", "SOFR"; matched ignoring case.

        Returns:
            Calendar: The US calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def uzbekistan(market: builtins.str = 'UZSE') -> Calendar:
        r"""
        The Uzbek calendar.

        Args:
            market (str): "UZSE", the only market; matched ignoring case.

        Returns:
            Calendar: The Uzbek calendar for that market.

        Raises:
            ItofinError: If market is not one of the accepted names.
        """
    @staticmethod
    def joint(calendars: typing.Sequence[Calendar], rule: builtins.str = 'JoinHolidays') -> Calendar:
        r"""
        A calendar combining several others.

        Args:
            calendars (list[Calendar]): The calendars to combine; at least one.
            rule (str): "JoinHolidays" makes a day a holiday when it is one on
                any calendar; "JoinBusinessDays" makes it a business day when it
                is one on any calendar. Matched ignoring case.

        Returns:
            Calendar: The joint calendar.

        Raises:
            ItofinError: If calendars is empty or rule is not one of the two
                accepted names.
        """
    def is_business_day(self, date: Date) -> builtins.bool:
        r"""
        Whether date is a business day on this calendar.

        Args:
            date (Date): The date to test.

        Returns:
            bool: True when date is neither a weekend day nor a holiday.

        Raises:
            ItofinError: If date is the null date or past the calendar's
                tabulated horizon.
        """
    def is_holiday(self, date: Date) -> builtins.bool:
        r"""
        Whether date is a holiday on this calendar, weekends included.

        Args:
            date (Date): The date to test.

        Returns:
            bool: True when date is not a business day.

        Raises:
            ItofinError: If date is the null date or past the calendar's
                tabulated horizon.
        """
    def is_weekend(self, date: Date) -> builtins.bool:
        r"""
        Whether date falls on this calendar's weekend, which for a market whose
        weekend moved over time depends on the date and not only its weekday.

        Args:
            date (Date): The date to test.

        Returns:
            bool: True when date is a weekend day.

        Raises:
            ItofinError: If date is the null date or past the calendar's
                tabulated horizon.
        """
    def holiday_list(self, from_date: Date, to_date: Date, include_weekends: builtins.bool = False) -> builtins.list[Date]:
        r"""
        The holidays between two dates, both inclusive.

        Args:
            from_date (Date): The first date of the range.
            to_date (Date): The last date of the range.
            include_weekends (bool): Also list the weekend days; off by default.

        Returns:
            list[Date]: The holidays in the range, in order.

        Raises:
            ItofinError: If either date is the null date, if to_date is before
                from_date, or if a date is past the calendar's tabulated
                horizon.
        """
    def business_days_between(self, from_date: Date, to_date: Date, include_first: builtins.bool = True, include_last: builtins.bool = False) -> builtins.int:
        r"""
        The number of business days between two dates.

        Args:
            from_date (Date): The first date of the range.
            to_date (Date): The last date of the range.
            include_first (bool): Count from_date when it is a business day; on
                by default.
            include_last (bool): Count to_date when it is a business day; off by
                default.

        Returns:
            int: The business-day count, negated when from_date is after to_date.

        Raises:
            ItofinError: If either date is the null date or past the
                calendar's tabulated horizon.
        """
    def adjust(self, date: Date, convention: BusinessDayConvention) -> Date:
        r"""
        Roll a date to the nearest business day.

        Args:
            date (Date): The date to roll.
            convention (BusinessDayConvention): The rolling rule to apply.

        Returns:
            Date: The adjusted date, unchanged when it is already a business day.

        Raises:
            ItofinError: If date is the null date or past the calendar's
                tabulated horizon.
        """
    def advance(self, date: Date, n: builtins.int, unit: builtins.str, convention: BusinessDayConvention, end_of_month: builtins.bool) -> Date:
        r"""
        Advance a date by n units and adjust the result.

        Args:
            date (Date): The date to advance from.
            n (int): The number of units to advance, which may be negative.
            unit (str): One of "Days", "Weeks", "Months", "Years".
            convention (BusinessDayConvention): The rule the advanced date is rolled under.
            end_of_month (bool): Keep the result on the month end when the starting
                date is one.

        Returns:
            Date: The advanced and adjusted date.

        Raises:
            ItofinError: If unit is not one of the four accepted strings, or if
                date is the null date or past the calendar's tabulated horizon.
        """
    def __eq__(self, other: Calendar) -> builtins.bool:
        r"""
        Equality by calendar name, so two independently built TARGET calendars
        are equal and a calendar read back off a curve equals its factory call.

        Args:
            other (object): The calendar to compare against.

        Returns:
            bool: True when both carry the same name.
        """
    def __hash__(self) -> builtins.int:
        r"""
        Hashes the calendar name, the field equality compares.

        Returns:
            int: The hash of the name, so equal calendars hash equal.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Return the calendar and its name.

        Returns:
            str: The calendar as Calendar(name).
        """

@typing.final
class Date:
    r"""
    A calendar date with a validation guard.

    Every constructor and every arithmetic result is range-checked before the
    core is reached, so an out-of-range date is an error rather than a panic.
    """
    @property
    def year(self) -> builtins.int:
        r"""
        The year.
        """
    @property
    def month(self) -> builtins.int:
        r"""
        The month, from 1 to 12.
        """
    @property
    def day(self) -> builtins.int:
        r"""
        The day of the month.
        """
    def __init__(self, day: builtins.int, month: builtins.int, year: builtins.int) -> None:
        r"""
        Build a date from its three components.

        Args:
            day (int): The day of the month, within the length of that month.
            month (int): The month, from 1 to 12.
            year (int): The year, from 1901 to 2199.

        Raises:
            ItofinError: If month is outside [1, 12], year is outside
                [1901, 2199], or day is outside the length of that month.
        """
    def __add__(self, days: builtins.int) -> Date:
        r"""
        Shift the date forward by a number of calendar days.

        Args:
            days (int): The number of calendar days to add.

        Returns:
            Date: The shifted date.

        Raises:
            ItofinError: If the result falls outside the representable date
                range.
        """
    def __eq__(self, other: Date) -> builtins.bool:
        r"""
        Whether the two dates are the same calendar day.

        Args:
            other (object): The date to compare against.

        Returns:
            bool: True when both stand for the same day.
        """
    def __hash__(self) -> builtins.int:
        r"""
        Hashes the calendar day, the field equality compares.

        Returns:
            int: The hash of the date, so equal dates hash equal.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Return the constructor form of the date.

        Returns:
            str: The date as Date(day, month, year).
        """
    @typing.overload
    def __sub__(self, days: int) -> Date:
        r"""
        Shift the date back by a number of calendar days.

        Args:
            days (int): The number of calendar days to subtract.

        Returns:
            Date: The shifted date.

        Raises:
            ItofinError: If the result falls outside the representable date
                range.
        """
    @typing.overload
    def __sub__(self, other: Date) -> int:
        r"""
        The signed number of days from other to this date.

        Args:
            other (Date): The date to measure from.

        Returns:
            int: The signed day count between the two dates.
        """

@typing.final
class DayCounter:
    r"""
    A year-fraction convention.
    """
    @staticmethod
    def actual360() -> DayCounter:
        r"""
        The Actual/360 convention.

        Returns:
            DayCounter: An Actual/360 day counter.
        """
    @staticmethod
    def actual365_fixed() -> DayCounter:
        r"""
        The Actual/365 (Fixed) convention.

        Returns:
            DayCounter: An Actual/365 (Fixed) day counter.
        """
    @staticmethod
    def actual_actual_isda() -> DayCounter:
        r"""
        The Actual/Actual (ISDA) convention.

        Returns:
            DayCounter: An Actual/Actual day counter on the ISDA convention.
        """
    @staticmethod
    def thirty360_bond_basis() -> DayCounter:
        r"""
        The 30/360 (Bond Basis) convention.

        Returns:
            DayCounter: A 30/360 day counter on the bond-basis convention.
        """
    def year_fraction(self, d1: Date, d2: Date) -> builtins.float:
        r"""
        The period [d1, d2] as a fraction of a year under this convention.

        Args:
            d1 (Date): The start of the period.
            d2 (Date): The end of the period.

        Returns:
            float: The year fraction between the two dates.
        """
    def __eq__(self, other: DayCounter) -> builtins.bool:
        r"""
        Equality by convention name, so two independently built Actual360s
        are equal.

        Args:
            other (object): The day counter to compare against.

        Returns:
            bool: True when both carry the same convention name.
        """
    def __hash__(self) -> builtins.int:
        r"""
        Hashes the convention name, the field equality compares.

        Returns:
            int: The hash of the convention name, so equal day counters hash equal.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Return the day counter and its convention name.

        Returns:
            str: The day counter as DayCounter(name).
        """

@typing.final
class Period:
    r"""
    A signed length in one calendar unit (unit: Days, Weeks, Months, Years).
    """
    def __init__(self, n: builtins.int, unit: builtins.str) -> None:
        r"""
        Build a period of n units.

        Args:
            n (int): The length, which may be negative.
            unit (str): One of "Days", "Weeks", "Months", "Years".

        Raises:
            ItofinError: If unit is not one of the four accepted strings.
        """
    def __eq__(self, other: Period) -> builtins.bool:
        r"""
        Semantic equality: 7 Days equals 1 Week and 12 Months equals 1 Year,
        while an undecidable pair such as 30 Days against 1 Month is not equal.

        Args:
            other (object): The period to compare against.

        Returns:
            bool: True when the two lengths are decidably the same.
        """
    def __hash__(self) -> builtins.int:
        r"""
        Hashes the canonical form, so equal periods hash equal.

        Normalizing collapses 7 Days onto 1 Week, 12 Months onto 1 Year and
        every zero length onto 0 Days before the hash is taken.

        Returns:
            int: The hash of the normalized length and unit.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Return the constructor form of the period.

        Returns:
            str: The period as Period(length, unit).
        """

@typing.final
class Schedule:
    r"""
    A sequence of coupon dates built through MakeSchedule.

    termination_convention rolls the last date only, and defaults to
    convention. CDS conventions need the two to differ: a credit helper leaves
    its maturity unadjusted while paying Following.
    """
    def __init__(self, start: Date, end: Date, frequency: Frequency, calendar: Calendar, convention: BusinessDayConvention, rule: DateGeneration = DateGeneration.Forward, termination_convention: typing.Optional[BusinessDayConvention] = None) -> None:
        r"""
        Build the schedule.

        Args:
            start (Date): The effective date, which must be strictly before end.
            end (Date): The termination date.
            frequency (Frequency): The coupon frequency the interior dates are spaced at.
            calendar (Calendar): The calendar the dates roll on.
            convention (BusinessDayConvention): The rule every date but the last is rolled under.
            rule (DateGeneration): The date-generation rule; defaults to Forward.
            termination_convention (BusinessDayConvention | None): The rule the last date is rolled under;
                None applies convention to it as well.

        Raises:
            ItofinError: If start is not strictly before end.
        """
    def size(self) -> builtins.int:
        r"""
        The number of dates in the schedule.

        Returns:
            int: The date count, one more than the number of periods.
        """
    def date(self, i: builtins.int) -> Date:
        r"""
        The i-th date in the schedule.

        Args:
            i (int): The zero-based index into the dates.

        Returns:
            Date: The date at that index.

        Raises:
            ItofinError: If i is out of range.
        """
    def dates(self) -> builtins.list[Date]:
        r"""
        All the schedule dates.

        Returns:
            list[Date]: The dates in order, from the effective date to the termination date.
        """

@typing.final
class BusinessDayConvention:
    r"""
    A holiday-rolling rule. Every core variant is covered; the four listed
    last are appended, so the integer values of the first three are unchanged.
    """
    ModifiedFollowing: typing.ClassVar[BusinessDayConvention]
    Following: typing.ClassVar[BusinessDayConvention]
    Unadjusted: typing.ClassVar[BusinessDayConvention]
    Preceding: typing.ClassVar[BusinessDayConvention]
    ModifiedPreceding: typing.ClassVar[BusinessDayConvention]
    HalfMonthModifiedFollowing: typing.ClassVar[BusinessDayConvention]
    Nearest: typing.ClassVar[BusinessDayConvention]
    def __new__(cls, _unconstructible: typing.NoReturn) -> BusinessDayConvention: ...
    def __int__(self) -> builtins.int: ...
    __hash__: typing.ClassVar[None]  # type: ignore[assignment]

@typing.final
class DateGeneration:
    r"""
    The rule a Schedule generates its dates by.

    Backward and Forward roll from one end of the range to the other; Zero keeps
    only the two endpoints; the ThirdWednesday and Twentieth families snap the
    interior dates onto an IMM Wednesday or the twentieth of the month. A
    Schedule builds under the three CDS rules, but SpreadCdsHelper rejects them:
    their maturity comes from a core routine that is not ported yet.
    """
    Backward: typing.ClassVar[DateGeneration]
    Forward: typing.ClassVar[DateGeneration]
    Zero: typing.ClassVar[DateGeneration]
    ThirdWednesday: typing.ClassVar[DateGeneration]
    ThirdWednesdayInclusive: typing.ClassVar[DateGeneration]
    Twentieth: typing.ClassVar[DateGeneration]
    TwentiethIMM: typing.ClassVar[DateGeneration]
    OldCDS: typing.ClassVar[DateGeneration]
    CDS: typing.ClassVar[DateGeneration]
    CDS2015: typing.ClassVar[DateGeneration]
    def __new__(cls, _unconstructible: typing.NoReturn) -> DateGeneration: ...
    def __int__(self) -> builtins.int: ...
    __hash__: typing.ClassVar[None]  # type: ignore[assignment]

@typing.final
class Frequency:
    r"""
    A coupon or fixing frequency.

    Only the variants the ported fixtures use are surfaced; new ones are
    appended, so the integer values of the existing variants are unchanged.
    """
    Annual: typing.ClassVar[Frequency]
    Semiannual: typing.ClassVar[Frequency]
    Quarterly: typing.ClassVar[Frequency]
    Monthly: typing.ClassVar[Frequency]
    def __new__(cls, _unconstructible: typing.NoReturn) -> Frequency: ...
    def __int__(self) -> builtins.int: ...
    __hash__: typing.ClassVar[None]  # type: ignore[assignment]

def is_imm_date(date: Date, main_cycle: builtins.bool = False) -> builtins.bool:
    r"""
    Whether date is an IMM date.

    An IMM date is the third Wednesday of the month, and of March, June,
    September or December only when main_cycle is set.

    Args:
        date (Date): The date to test.
        main_cycle (bool): Restrict the test to the March/June/September/December
            cycle.

    Returns:
        bool: True when date is an IMM date under the selected cycle.
    """

def next_imm_date(date: Date, main_cycle: builtins.bool = False) -> Date:
    r"""
    The next IMM date strictly following date.

    Args:
        date (Date): The date to start from; the result is strictly after it.
        main_cycle (bool): Restrict the result to the March/June/September/December
            cycle.

    Returns:
        Date: The next IMM date under the selected cycle.
    """
