# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
import typing
__all__ = [
    "DirectionIntegers",
    "GaussianLowDiscrepancySequenceGenerator",
    "GaussianRandomGenerator",
    "GaussianRandomSequenceGenerator",
    "HaltonRsg",
    "SobolRsg",
    "UniformRandomGenerator",
    "UniformRandomSequenceGenerator",
]

@typing.final
class GaussianLowDiscrepancySequenceGenerator:
    r"""
    The Gaussian low-discrepancy sequence generator: Sobol points mapped
    through the inverse cumulative normal, QuantLib's
    `InverseCumulativeRsg<SobolRsg, InverseCumulativeNormal>`.

    The first draw is 0.0 in every dimension, the inverse normal of the first
    Sobol point 0.5. The generator copies the Sobol generator it is built from,
    as QuantLib does.
    """
    def __init__(self, rsg: SobolRsg) -> None:
        r"""
        Build a Gaussian sequence generator over a copy of a Sobol generator.

        Args:
            rsg (SobolRsg): The Sobol generator to copy the state from; its
                dimension is the dimension here.
        """
    def dimension(self) -> builtins.int:
        r"""
        The number of draws per sequence.

        Returns:
            int: The dimension the generator was built with.
        """
    def next_sequence(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Draw the next sequence.

        Returns:
            numpy.ndarray: A float64 array of shape (dimension,) of standard
            normal deviates.
        """
    def last_sequence(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        The most recently drawn sequence, without advancing.

        Returns:
            numpy.ndarray: A float64 array of shape (dimension,); all zeros
            before the first draw.
        """
    def next_sequences(self, count: builtins.int) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Draw many sequences in one call.

        Args:
            count (int): The number of sequences to draw.

        Returns:
            numpy.ndarray: A float64 array of shape (count, dimension), row i
            being what the (i + 1)-th next_sequence() call would have returned.

        Raises:
            ItofinError: If a buffer of count sequences cannot be allocated.
        """

@typing.final
class GaussianRandomGenerator:
    r"""
    The Gaussian pseudo-random number generator: the polar Box-Muller
    transform over a Mersenne Twister, QuantLib's
    `BoxMullerGaussianRng<MersenneTwisterUniformRng>`.

    Each pair of uniform draws yields two standard normal deviates; the second
    is cached and returned by the next call, as in QuantLib.
    """
    def __init__(self, rng: UniformRandomGenerator) -> None:
        r"""
        Build a generator over a copy of a uniform generator.

        Args:
            rng (UniformRandomGenerator): The uniform generator to copy the
                state from.
        """
    @staticmethod
    def with_seed(seed: builtins.int = 0) -> GaussianRandomGenerator:
        r"""
        Build a generator over a fresh Mersenne Twister.

        Args:
            seed (int): The 32-bit seed; 0 draws a random seed.

        Returns:
            GaussianRandomGenerator: The seeded generator.
        """
    def next_gaussian(self) -> builtins.float:
        r"""
        Draw the next standard normal deviate.

        Returns:
            float: A deviate with mean 0 and standard deviation 1.
        """
    def next_gaussians(self, count: builtins.int) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Draw many standard normal deviates in one call.

        Args:
            count (int): The number of deviates to draw.

        Returns:
            numpy.ndarray: A float64 array of shape (count,), holding exactly
            what count successive next_gaussian() calls would have returned.

        Raises:
            ItofinError: If a buffer of count draws cannot be allocated.
        """

@typing.final
class GaussianRandomSequenceGenerator:
    r"""
    The Gaussian random sequence generator: uniform Mersenne-Twister sequences
    mapped through the inverse cumulative normal, QuantLib's
    `InverseCumulativeRsg<RandomSequenceGenerator<MersenneTwisterUniformRng>,
    InverseCumulativeNormal>`.

    This is the `PseudoRandom` policy the Monte Carlo engines draw their paths
    from: with_seed(dimension, seed) reproduces the engines' generator for the
    same dimension and seed. The generator copies the uniform sequence generator
    it is built from, as QuantLib does.
    """
    def __init__(self, usg: UniformRandomSequenceGenerator) -> None:
        r"""
        Build a Gaussian sequence generator over a copy of a uniform one.

        Args:
            usg (UniformRandomSequenceGenerator): The uniform sequence generator
                to copy the state from; its dimension is the dimension here.
        """
    @staticmethod
    def with_seed(dimension: builtins.int, seed: builtins.int = 0) -> GaussianRandomSequenceGenerator:
        r"""
        Build a Gaussian sequence generator over a fresh Mersenne Twister.

        Args:
            dimension (int): The number of draws per sequence, at least 1.
            seed (int): The 32-bit seed; 0 draws a random seed.

        Returns:
            GaussianRandomSequenceGenerator: The seeded sequence generator.

        Raises:
            ItofinError: If dimension is 0.
        """
    def dimension(self) -> builtins.int:
        r"""
        The number of draws per sequence.

        Returns:
            int: The dimension the generator was built with.
        """
    def next_sequence(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Draw the next sequence.

        Returns:
            numpy.ndarray: A float64 array of shape (dimension,) of standard
            normal deviates.
        """
    def last_sequence(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        The most recently drawn sequence, without advancing.

        Returns:
            numpy.ndarray: A float64 array of shape (dimension,); all zeros
            before the first draw.
        """
    def next_sequences(self, count: builtins.int) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Draw many sequences in one call.

        Args:
            count (int): The number of sequences to draw.

        Returns:
            numpy.ndarray: A float64 array of shape (count, dimension), row i
            being what the (i + 1)-th next_sequence() call would have returned.

        Raises:
            ItofinError: If a buffer of count sequences cannot be allocated.
        """

@typing.final
class HaltonRsg:
    r"""
    The Halton low-discrepancy sequence generator, QuantLib's `HaltonRsg`
    with randomStart and randomShift both off.

    Draw k (1-based) is the radical inverse of k in a distinct prime base per
    dimension: base 2 for the first dimension, 3 for the second, 5 for the
    third, and so on. The sequence is deterministic; the randomized start and
    shift of QuantLib's default constructor are not exposed, being deferred in
    the core.
    """
    def __init__(self, dimension: builtins.int) -> None:
        r"""
        Build a Halton generator.

        Args:
            dimension (int): The number of draws per point, at least 1.

        Raises:
            ItofinError: If dimension is 0.
        """
    def dimension(self) -> builtins.int:
        r"""
        The number of draws per point.

        Returns:
            int: The dimension the generator was built with.
        """
    def next_sequence(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Draw the next Halton point.

        Returns:
            numpy.ndarray: A float64 array of shape (dimension,), every entry
            inside [0, 1).
        """
    def last_sequence(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        The most recently drawn point, without advancing.

        Returns:
            numpy.ndarray: A float64 array of shape (dimension,); all zeros
            before the first draw.
        """
    def next_sequences(self, count: builtins.int) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Draw many points in one call.

        Args:
            count (int): The number of points to draw.

        Returns:
            numpy.ndarray: A float64 array of shape (count, dimension), row i
            being what the (i + 1)-th next_sequence() call would have returned.

        Raises:
            ItofinError: If a buffer of count points cannot be allocated.
        """

@typing.final
class SobolRsg:
    r"""
    The Sobol low-discrepancy sequence generator, QuantLib's `SobolRsg`.

    Successive draws fill the unit hypercube evenly rather than randomly, so a
    Monte Carlo estimate over them converges faster than over pseudo-random
    draws. The first draw is 0.5 in every dimension, and every draw lies
    strictly inside (0, 1). The generator is deterministic for a given seed:
    the seed only matters for dimensions beyond the tabulated initializers.
    """
    def __init__(self, dimension: builtins.int, seed: builtins.int = 0, direction_integers: DirectionIntegers = DirectionIntegers.Jaeckel, use_gray_code: builtins.bool = True) -> None:
        r"""
        Build a Sobol generator.

        Args:
            dimension (int): The number of draws per sequence, from 1 to the
                number of primitive polynomials shipped (21200).
            seed (int): The seed for the free direction integers past the
                tabulated dimensions; used literally, so 0 is a fixed seed.
            direction_integers (DirectionIntegers): The direction-integer
                table, Jaeckel by default as in QuantLib.
            use_gray_code (bool): Generate through the Gray-code counter (the
                QuantLib default) rather than the plain counter.

        Raises:
            ItofinError: If dimension is 0 or exceeds 21200.
        """
    def dimension(self) -> builtins.int:
        r"""
        The number of draws per sequence.

        Returns:
            int: The dimension the generator was built with.
        """
    def next_sequence(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Draw the next Sobol point.

        Returns:
            numpy.ndarray: A float64 array of shape (dimension,), every entry
            strictly inside (0, 1).
        """
    def last_sequence(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        The most recently drawn point, without advancing.

        Returns:
            numpy.ndarray: A float64 array of shape (dimension,); all zeros
            before the first draw.
        """
    def next_int32_sequence(self) -> numpy.typing.NDArray[numpy.uint32]:
        r"""
        Draw the next point as raw 32-bit Sobol integers.

        Returns:
            numpy.ndarray: A uint32 array of shape (dimension,); the float
            point is this array scaled by 2^-32.
        """
    def next_sequences(self, count: builtins.int) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Draw many points in one call.

        Args:
            count (int): The number of points to draw.

        Returns:
            numpy.ndarray: A float64 array of shape (count, dimension), row i
            being what the (i + 1)-th next_sequence() call would have returned.

        Raises:
            ItofinError: If a buffer of count points cannot be allocated.
        """
    def skip_to(self, n: builtins.int) -> numpy.typing.NDArray[numpy.uint32]:
        r"""
        Skip to the n-th point of the sequence and return it as raw integers.

        QuantLib's skipTo, whose counter semantics are kept: with the Gray-code
        counter the following draw returns point n + 1, unless it is the very
        first draw made on the generator, which returns point n itself; with
        the plain counter the following draw returns point n. The float point
        is the returned array scaled by 2^-32.

        Args:
            n (int): The 0-based index of the point to skip to.

        Returns:
            numpy.ndarray: A uint32 array of shape (dimension,), point n as
            raw Sobol integers.

        Raises:
            ItofinError: If n is 2^32 - 1, past the sequence period.
        """

@typing.final
class UniformRandomGenerator:
    r"""
    The uniform pseudo-random number generator: a Mersenne Twister (MT19937)
    with period 2^19937 - 1, QuantLib's `MersenneTwisterUniformRng`.

    Draws are deterministic for a non-zero seed: the same seed reproduces the
    same stream bitwise, on every platform. A seed of 0 draws a random seed
    from the core seed generator, so two zero-seeded generators diverge.
    """
    def __init__(self, seed: builtins.int = 0) -> None:
        r"""
        Build a generator from a seed.

        Args:
            seed (int): The 32-bit seed. 0 (the default) draws a random seed
                from the core seed generator, matching QuantLib.
        """
    @staticmethod
    def from_seeds(seeds: typing.Sequence[builtins.int]) -> UniformRandomGenerator:
        r"""
        Build a generator from an array of seeds, the reference
        `init_by_array` initialization.

        Args:
            seeds (list[int]): The 32-bit seed words; at least one.

        Returns:
            UniformRandomGenerator: The generator initialized from the array.

        Raises:
            ItofinError: If seeds is empty.
        """
    def next_real(self) -> builtins.float:
        r"""
        Draw the next uniform deviate.

        Returns:
            float: A deviate strictly inside (0, 1): the raw 32-bit output
            shifted by one half and scaled by 2^-32, so neither endpoint is
            ever returned.
        """
    def next_u32(self) -> builtins.int:
        r"""
        Draw the next raw 32-bit output.

        Returns:
            int: An integer uniform over [0, 2^32 - 1].
        """
    def next_reals(self, count: builtins.int) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Draw many uniform deviates in one call.

        Args:
            count (int): The number of deviates to draw.

        Returns:
            numpy.ndarray: A float64 array of shape (count,), holding exactly
            what count successive next_real() calls would have returned.

        Raises:
            ItofinError: If a buffer of count draws cannot be allocated.
        """

@typing.final
class UniformRandomSequenceGenerator:
    r"""
    The uniform random sequence generator: `dimension` Mersenne-Twister draws
    per sequence, QuantLib's `RandomSequenceGenerator<MersenneTwisterUniformRng>`.

    The generator copies the scalar generator it is built from, as QuantLib
    does, so later draws on the original do not affect the sequence.
    """
    def __init__(self, dimension: builtins.int, rng: UniformRandomGenerator) -> None:
        r"""
        Build a sequence generator over a copy of a scalar generator.

        Args:
            dimension (int): The number of draws per sequence, at least 1.
            rng (UniformRandomGenerator): The scalar generator to copy the
                state from.

        Raises:
            ItofinError: If dimension is 0.
        """
    @staticmethod
    def with_seed(dimension: builtins.int, seed: builtins.int = 0) -> UniformRandomSequenceGenerator:
        r"""
        Build a sequence generator over a fresh Mersenne Twister.

        Args:
            dimension (int): The number of draws per sequence, at least 1.
            seed (int): The 32-bit seed; 0 draws a random seed.

        Returns:
            UniformRandomSequenceGenerator: The seeded sequence generator.

        Raises:
            ItofinError: If dimension is 0.
        """
    def dimension(self) -> builtins.int:
        r"""
        The number of draws per sequence.

        Returns:
            int: The dimension the generator was built with.
        """
    def next_sequence(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Draw the next sequence.

        Returns:
            numpy.ndarray: A float64 array of shape (dimension,), every entry
            strictly inside (0, 1).
        """
    def last_sequence(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        The most recently drawn sequence, without advancing.

        Returns:
            numpy.ndarray: A float64 array of shape (dimension,); all zeros
            before the first draw.
        """
    def next_sequences(self, count: builtins.int) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Draw many sequences in one call.

        Args:
            count (int): The number of sequences to draw.

        Returns:
            numpy.ndarray: A float64 array of shape (count, dimension), row i
            being what the (i + 1)-th next_sequence() call would have returned.

        Raises:
            ItofinError: If a buffer of count sequences cannot be allocated.
        """

@typing.final
class DirectionIntegers:
    r"""
    The choice of free direction integers for the Sobol dimensions beyond the
    first, QuantLib's `SobolRsg::DirectionIntegers`.

    Jaeckel is QuantLib's default. Unit uses the unit initialization for every
    dimension; the others are the tabulated initializers shipped with QuantLib,
    with a seeded Mersenne Twister drawing the free integers past each table.
    """
    Unit: typing.ClassVar[DirectionIntegers]
    Jaeckel: typing.ClassVar[DirectionIntegers]
    SobolLevitan: typing.ClassVar[DirectionIntegers]
    SobolLevitanLemieux: typing.ClassVar[DirectionIntegers]
    JoeKuoD5: typing.ClassVar[DirectionIntegers]
    JoeKuoD6: typing.ClassVar[DirectionIntegers]
    JoeKuoD7: typing.ClassVar[DirectionIntegers]
    Kuo: typing.ClassVar[DirectionIntegers]
    Kuo2: typing.ClassVar[DirectionIntegers]
    Kuo3: typing.ClassVar[DirectionIntegers]
    def __new__(cls, _unconstructible: typing.NoReturn) -> DirectionIntegers: ...
    def __int__(self) -> builtins.int: ...
    __hash__: typing.ClassVar[None]  # type: ignore[assignment]
