[package]
name = "libitofin-ffi"
version.workspace = true
edition.workspace = true
license = "BSD-3-Clause"
description = "C ABI for libitofin"
repository = "https://github.com/benbenbang/libitofin"

[lib]
name = "itofin_ffi"
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
libitofin = { path = "../libitofin" }
