# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "EndCriteria",
    "LevenbergMarquardt",
]

@typing.final
class EndCriteria:
    r"""
    The optimizer stopping rule.

    Carries the iteration cap and the stationarity thresholds an optimization
    run is tested against.
    """
    def __init__(self, max_iterations: builtins.int, max_stationary_state_iterations: typing.Optional[builtins.int], root_epsilon: builtins.float, function_epsilon: builtins.float, gradient_norm_epsilon: typing.Optional[builtins.float]) -> None:
        r"""
        Initialize the criteria.

        Args:
            max_iterations (int): The iteration count at which the run stops.
            max_stationary_state_iterations (int | None): How many consecutive stationary
                iterations are tolerated before the run is called converged;
                None defaults to min(max_iterations / 2, 100).
            root_epsilon (float): The variation of the independent variable below which
                an iteration counts as stationary.
            function_epsilon (float): The variation of the function value below which an
                iteration counts as stationary, and, for a cost function known
                to be positive, the value below which the run has converged.
            gradient_norm_epsilon (float | None): The gradient norm below which the run has
                converged; None defaults to function_epsilon.

        Raises:
            ItofinError: Unless 1 < max_stationary_state_iterations <
                max_iterations, or if any epsilon is negative or non-finite.
        """

@typing.final
class LevenbergMarquardt:
    r"""
    The least-squares optimizer used to fit model parameters.

    Wraps the MINPACK lmdif routine. The Jacobian comes from a built-in
    forward-difference scheme by default; the cost function's own jacobian
    method is used instead when use_cost_functions_jacobian is set.
    """
    def __init__(self, epsfcn: builtins.float = 1e-08, xtol: builtins.float = 1e-08, gtol: builtins.float = 1e-08, use_cost_functions_jacobian: builtins.bool = False) -> None:
        r"""
        Initialize the optimizer; the defaults are QuantLib's.

        Args:
            epsfcn (float): The finite-difference step seed used when the Jacobian is
                computed by differences.
            xtol (float): The tolerance on the independent variable.
            gtol (float): The tolerance on the gradient.
            use_cost_functions_jacobian (bool): Use the cost function's own jacobian
                method (a central difference, order 2 but costlier) instead of
                the built-in forward-difference scheme.
        """
