"""Runtime source shim for the native ``itofin.optimization`` submodule.

The real ``itofin.optimization`` is a compiled submodule registered into
``sys.modules`` by the extension; it wins at import time, so nothing here
runs. This file exists only so static type checkers resolve
``from itofin.optimization import ...`` from ``optimization/__init__.pyi`` without a
``reportMissingModuleSource`` warning.

Auto-generated by scripts/gen_submodule_shims.py from ``optimization/__init__.pyi``; do not edit or delete by hand.
"""
