# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from itofin import optimize
import typing
__all__ = [
    "BoundaryConstraint",
    "CompositeConstraint",
    "ConjugateGradient",
    "DifferentialEvolution",
    "EndCriteria",
    "LevenbergMarquardt",
    "NoConstraint",
    "ParticleSwarm",
    "PositiveConstraint",
    "Simplex",
    "SteepestDescent",
]

@typing.final
class BoundaryConstraint:
    r"""
    An inclusive lower and upper bound for every parameter.
    """
    def __init__(self, low: builtins.float, high: builtins.float) -> None:
        r"""
        Build a bound with finite, ordered endpoints.
        """

@typing.final
class CompositeConstraint:
    r"""
    The intersection of two reusable constraints.
    """
    def __init__(self, a: NoConstraint | PositiveConstraint | BoundaryConstraint | CompositeConstraint, b: NoConstraint | PositiveConstraint | BoundaryConstraint | CompositeConstraint) -> None:
        r"""
        Copy both children, so they may be released independently.
        """

@typing.final
class ConjugateGradient:
    r"""
    The conjugate-gradient method for calibration.
    """
    def __init__(self) -> None:
        r"""
        Build a conjugate-gradient method with the core Armijo line search.
        """

@typing.final
class DifferentialEvolution:
    r"""
    Bounded global calibration in projected free-parameter order.
    The complete search box must satisfy the model's constraint.
    """
    def __init__(self, bounds: typing.Sequence[tuple[builtins.float, builtins.float]], *, seed: builtins.int = 0, population_size: typing.Optional[builtins.int] = None, initial_population: typing.Optional[typing.Sequence[typing.Sequence[builtins.float]]] = None, xatol: typing.Optional[builtins.float] = None, fatol: typing.Optional[builtins.float] = None, mutation: builtins.float = 0.8, recombination: builtins.float = 0.9, maxiter: typing.Optional[builtins.int] = None, maxfev: typing.Optional[builtins.int] = None) -> None:
        r"""
        Construct a bounded, deterministic DE/rand/1/bin calibration method.
        Bounds and population coordinates use the free parameter order.
        Invalid candidates abort before pricing rather than receiving a penalty.
        """
    def last_result(self) -> typing.Optional[optimize.OptimizeResult]:
        r"""
        Copy the exact last global result, or None before a completed run.
        Exhausted runs are retained without being labelled successful.
        """

@typing.final
class EndCriteria:
    r"""
    The optimizer stopping rule.

    Carries the iteration cap and the stationarity thresholds an optimization
    run is tested against.
    """
    def __init__(self, max_iterations: builtins.int, max_stationary_state_iterations: typing.Optional[builtins.int], root_epsilon: builtins.float, function_epsilon: builtins.float, gradient_norm_epsilon: typing.Optional[builtins.float]) -> None:
        r"""
        Initialize the criteria.

        Args:
            max_iterations (int): The iteration count at which the run stops.
            max_stationary_state_iterations (int | None): How many consecutive stationary
                iterations are tolerated before the run is called converged;
                None defaults to min(max_iterations / 2, 100).
            root_epsilon (float): The variation of the independent variable below which
                an iteration counts as stationary.
            function_epsilon (float): The variation of the function value below which an
                iteration counts as stationary, and, for a cost function known
                to be positive, the value below which the run has converged.
            gradient_norm_epsilon (float | None): The gradient norm below which the run has
                converged; None defaults to function_epsilon.

        Raises:
            ItofinError: Unless 1 < max_stationary_state_iterations <
                max_iterations, or if any epsilon is negative or non-finite.
        """

@typing.final
class LevenbergMarquardt:
    r"""
    The least-squares optimizer used to fit model parameters.

    Wraps the MINPACK lmdif routine. The Jacobian comes from a built-in
    forward-difference scheme by default; the cost function's own jacobian
    method is used instead when use_cost_functions_jacobian is set.
    """
    def __init__(self, epsfcn: builtins.float = 1e-08, xtol: builtins.float = 1e-08, gtol: builtins.float = 1e-08, use_cost_functions_jacobian: builtins.bool = False) -> None:
        r"""
        Initialize the optimizer; the defaults are QuantLib's.

        Args:
            epsfcn (float): The finite-difference step seed used when the Jacobian is
                computed by differences.
            xtol (float): The tolerance on the independent variable.
            gtol (float): The tolerance on the gradient.
            use_cost_functions_jacobian (bool): Use the cost function's own jacobian
                method (a central difference, order 2 but costlier) instead of
                the built-in forward-difference scheme.
        """

@typing.final
class NoConstraint:
    r"""
    A constraint that accepts every parameter vector.
    """
    def __init__(self) -> None:
        r"""
        Build an unconstrained parameter region.
        """

@typing.final
class ParticleSwarm:
    r"""
    Bounded global calibration in projected free-parameter order.
    The complete search box must satisfy the model's constraint.
    """
    def __init__(self, bounds: typing.Sequence[tuple[builtins.float, builtins.float]], *, seed: builtins.int = 0, population_size: typing.Optional[builtins.int] = None, initial_population: typing.Optional[typing.Sequence[typing.Sequence[builtins.float]]] = None, xatol: typing.Optional[builtins.float] = None, fatol: typing.Optional[builtins.float] = None, inertia: builtins.float = 0.7, cognitive: builtins.float = 1.4, social: builtins.float = 1.4, velocity_clamp: builtins.float = 0.2, maxiter: typing.Optional[builtins.int] = None, maxfev: typing.Optional[builtins.int] = None) -> None:
        r"""
        Construct a bounded, deterministic global-best particle swarm calibration method.
        Bounds and population coordinates use the free parameter order.
        Invalid candidates abort before pricing rather than receiving a penalty.
        """
    def last_result(self) -> typing.Optional[optimize.OptimizeResult]:
        r"""
        Copy the exact last global result, or None before a completed run.
        Exhausted runs are retained without being labelled successful.
        """

@typing.final
class PositiveConstraint:
    r"""
    A constraint requiring every parameter to be strictly positive.
    """
    def __init__(self) -> None:
        r"""
        Require each parameter to be strictly positive.
        """

@typing.final
class Simplex:
    r"""
    The downhill simplex method for derivative-free calibration.
    """
    def __init__(self, lambda_: builtins.float) -> None:
        r"""
        Build a simplex with a finite, positive characteristic length.

        Raises:
            ValueError: If lambda_ is zero, negative or non-finite.
        """

@typing.final
class SteepestDescent:
    r"""
    The steepest-descent method for calibration.
    """
    def __init__(self) -> None:
        r"""
        Build a steepest-descent method with the core Armijo line search.
        """
