# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
from . import cashflows
from . import indexes
from . import instruments
from . import models
from . import optimization
from . import pricingengines
from . import processes
from . import quotes
from . import randomnumbers
from . import results
from . import termstructures
from . import time
__all__ = [
    "ItofinError",
    "Settings",
    "cashflows",
    "indexes",
    "instruments",
    "models",
    "optimization",
    "pricingengines",
    "processes",
    "quotes",
    "randomnumbers",
    "results",
    "termstructures",
    "time",
]

__version__: builtins.str
class ItofinError(builtins.Exception):
    r"""
    Error raised by the itofin API, carrying the located message.

    Every fallible core call surfaces as this exception, whose message is the
    located form "file:line: message".
    """
    ...

@typing.final
class Settings:
    r"""
    The explicit, non-global evaluation-date store (D5).

    There is no global singleton: the exact settings object passed to a
    construction is the one it reads, so instruments built against different
    Settings do not see each other's evaluation date.
    """
    def __init__(self) -> None:
        r"""
        Create settings with no evaluation date set.
        """
    def set_evaluation_date(self, date: time.Date) -> None:
        r"""
        Set the evaluation date, notifying observers if it changed.

        The new date is in place before the notification goes out, so an
        observer that recomputes on the update reads the date that triggered it.

        Args:
            date (time.Date): The new evaluation date. Observers are notified only when this
                differs from the date already set.
        """
    def set_include_todays_cash_flows(self, value: typing.Optional[builtins.bool]) -> None:
        r"""
        Set whether cash flows on today's date enter an NPV; None clears.

        The flag is three-valued, as in the core.

        Args:
            value (bool | None): True or False decides the question outright; None clears it,
                restoring the unset state in which each pricing site applies its
                own default. The argument is required, so clearing is always
                deliberate.
        """
    def include_todays_cash_flows(self) -> typing.Optional[builtins.bool]:
        r"""
        Return the current setting, or None while it is unset.

        Returns:
            bool | None: The three-valued flag last set, or None if it has never been set or
            was cleared.
        """
