# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
import typing
from . import cashflows
from . import indexes
from . import instruments
from . import models
from . import optimization
from . import optimize
from . import pricingengines
from . import processes
from . import quotes
from . import randomnumbers
from . import results
from . import termstructures
from . import time
__all__ = [
    "DEFAULT_MAX_OUTPUT_VALUES",
    "ItofinError",
    "Settings",
    "cashflows",
    "gaussian_draws",
    "indexes",
    "instruments",
    "models",
    "optimization",
    "optimize",
    "pricingengines",
    "processes",
    "quotes",
    "randomnumbers",
    "results",
    "simulate_gbm",
    "termstructures",
    "time",
]

DEFAULT_MAX_OUTPUT_VALUES: builtins.int
__version__: builtins.str
class ItofinError(builtins.Exception):
    r"""
    Error raised by the itofin API, carrying the located message.

    Every fallible core call surfaces as this exception, whose message is the
    located form "file:line: message".
    """
    ...

@typing.final
class Settings:
    r"""
    The explicit, non-global evaluation-date store (D5).

    There is no global singleton: the exact settings object passed to a
    construction is the one it reads, so instruments built against different
    Settings do not see each other's evaluation date.
    """
    def __init__(self) -> None:
        r"""
        Create settings with no evaluation date set.
        """
    def set_evaluation_date(self, date: time.Date) -> None:
        r"""
        Set the evaluation date, notifying observers if it changed.

        The new date is in place before the notification goes out, so an
        observer that recomputes on the update reads the date that triggered it.

        Args:
            date (time.Date): The new evaluation date. Observers are notified only when this
                differs from the date already set.
        """
    def set_using_at_par_coupons(self, value: builtins.bool) -> None:
        r"""
        Select par or indexed Ibor coupon forecasting before constructing instruments.

        This setting does not invalidate already cached prices.
        """
    def using_at_par_coupons(self) -> builtins.bool:
        r"""
        Return whether Ibor coupons use par forecasting (the default).
        """
    def set_include_todays_cash_flows(self, value: typing.Optional[builtins.bool]) -> None:
        r"""
        Set whether cash flows on today's date enter an NPV; None clears.

        The flag is three-valued, as in the core.

        Args:
            value (bool | None): True or False decides the question outright; None clears it,
                restoring the unset state in which each pricing site applies its
                own default. The argument is required, so clearing is always
                deliberate.
        """
    def include_todays_cash_flows(self) -> typing.Optional[builtins.bool]:
        r"""
        Return the current setting, or None while it is unset.

        Returns:
            bool | None: The three-valued flag last set, or None if it has never been set or
            was cleared.
        """

def gaussian_draws(count: builtins.int, seed: builtins.int) -> numpy.typing.NDArray[numpy.float64]:
    r"""
    Draw standard normal values in the same MT19937/inverse-normal order as Go.

    Args:
        count (int): Number of draws, at most 16,777,216.
        seed (int): Nonzero 32-bit seed. Each call restarts the stream.

    Returns:
        numpy.ndarray: A float64 array of shape `(count,)`.

    Raises:
        ItofinError: If the count is outside the limit or the seed is zero.
    """

def simulate_gbm(initial: typing.Sequence[builtins.float], drift: typing.Sequence[builtins.float], volatility: typing.Sequence[builtins.float], horizon: builtins.float, steps: builtins.int, paths: builtins.int, seed: builtins.int, correlation: typing.Optional[typing.Sequence[builtins.float]] = None, terminal_only: builtins.bool = False, max_output_values: builtins.int = 0) -> numpy.typing.NDArray[numpy.float64]:
    r"""
    Generate exact-discretization correlated geometric Brownian paths.

    Draws are consumed path, time, asset; equal nonzero seeds and inputs are
    bit-identical to Go `SimulateGBM`. Initial values appear at time zero.

    Args:
        initial (list[float]): Positive initial asset values.
        drift (list[float]): Annualized arithmetic drifts, one per asset.
        volatility (list[float]): Nonnegative annualized volatilities.
        horizon (float): Nonnegative time horizon in units matching the rates.
        steps (int): Positive number of time intervals per path.
        paths (int): Positive number of independent paths.
        seed (int): Nonzero 32-bit seed.
        correlation (list[float] | None): Positive-definite row-major matrix;
            None selects identity.
        terminal_only (bool): Return final asset values without intermediate rows.
        max_output_values (int): Zero selects 16,777,216 float64 values (128 MiB);
            a positive value overrides this limit.

    Returns:
        numpy.ndarray: Float64 values shaped `(paths, steps + 1, assets)` or,
            with `terminal_only`, `(paths, assets)`.

    Raises:
        ItofinError: If inputs, correlation, or output size are invalid.
    """
