#!/usr/bin/env python3
"""Generate runtime source shims for itofin's native submodules.

The compiled extension registers ``itofin.time``, ``itofin.instruments`` and the
other submodules into ``sys.modules`` at load time. They exist only at runtime,
so a static type checker sees ``time/__init__.pyi`` with no matching source and
emits a yellow ``reportMissingModuleSource`` warning even though the types
resolve fine.

The fix is one inert ``<name>/__init__.py`` per submodule: Pyright then reads
types from the ``.pyi`` and stops warning, and the file never executes because
``sys.modules`` already holds the native module before any import resolves to it.
Its docstring is also what the API docs show as the submodule blurb, since a
generated stub carries no module docstring of its own.

This script keeps those shims in sync with the generated stubs: it writes a shim
for every ``python/itofin/<name>/__init__.pyi``, and removes any orphaned shim it
previously generated whose stub is gone. Run with ``--check`` to only report
drift; the default rewrites and exits non-zero on any change, matching the
autofix hook convention.
"""

from __future__ import annotations

# standard library
import sys
from pathlib import Path

MARKER = "generated by scripts/gen_submodule_shims.py"

PKG_DIR = Path(__file__).resolve().parent.parent / "python" / "itofin"


def shim_body(name: str) -> str:
    return (
        f'"""Runtime source shim for the native ``itofin.{name}`` submodule.\n'
        f"\n"
        f"The real ``itofin.{name}`` is a compiled submodule registered into\n"
        f"``sys.modules`` by the extension; it wins at import time, so nothing here\n"
        f"runs. This file exists only so static type checkers resolve\n"
        f"``from itofin.{name} import ...`` from ``{name}/__init__.pyi`` without a\n"
        f"``reportMissingModuleSource`` warning.\n"
        f"\n"
        f"Auto-{MARKER} from ``{name}/__init__.pyi``; do not edit or delete by hand.\n"
        f'"""\n'
    )


def desired_shims(pkg_dir: Path) -> dict[str, str]:
    return {pyi.parent.name: shim_body(pyi.parent.name) for pyi in sorted(pkg_dir.glob("*/__init__.pyi"))}


def is_generated_shim(path: Path) -> bool:
    return path.is_file() and MARKER in path.read_text(encoding="utf-8")


def orphans(pkg_dir: Path, wanted: dict[str, str]) -> list[Path]:
    found = list(pkg_dir.glob("*.py")) + list(pkg_dir.glob("*/__init__.py"))
    stale = []
    for py in sorted(found):
        name = py.parent.name if py.name == "__init__.py" else py.stem
        if py.parent == pkg_dir and py.name == "__init__.py":
            continue
        if name in wanted and py.name == "__init__.py":
            continue
        if is_generated_shim(py):
            stale.append(py)
    return stale


def run(pkg_dir: Path, check: bool) -> int:
    wanted = desired_shims(pkg_dir)
    changes: list[str] = []

    for name, body in wanted.items():
        target = pkg_dir / name / "__init__.py"
        current = target.read_text(encoding="utf-8") if target.exists() else None
        if current != body:
            changes.append(f"{'stale' if current is not None else 'missing'}: {name}/__init__.py")
            if not check:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(body, encoding="utf-8")

    for py in orphans(pkg_dir, wanted):
        changes.append(f"orphaned: {py.relative_to(pkg_dir)}")
        if not check:
            py.unlink()

    if changes:
        verb = "would update" if check else "updated"
        print(f"submodule shims {verb}:", file=sys.stderr)
        for c in changes:
            print(f"  {c}", file=sys.stderr)
        return 1
    return 0


def main() -> int:
    check = "--check" in sys.argv[1:]
    return run(PKG_DIR, check=check)


if __name__ == "__main__":
    raise SystemExit(main())
