#!/usr/bin/env python3
"""Regenerate the itofin type stubs and the runtime submodule shims.

This is the single entry point for the generated part of ``python/itofin``. It
runs three steps in order:

1. ``cargo run -p itofin-py --bin stub_gen`` writes one ``.pyi`` per module from
   the ``#[gen_stub_*]`` annotations on the Rust facade.
2. A post-process rewrites each generated stub. ``pyo3-stub-gen`` emits a
   constructor as ``def __new__(cls, ...) -> Class``; mkdocstrings renders the
   constructor signature and its parameter table only from ``__init__`` (its
   ``merge_init_into_class`` option), and ``filters: ["!^_"]`` drops the dunder
   entirely, so the whole constructor block would vanish from the API docs. The
   rewrite to ``def __init__(self, ...) -> None`` restores it and is also the
   correct stub for a type whose ``__init__`` is what callers invoke. The same
   pass models fieldless PyO3 enums as nonconstructible classes with typed
   class members and integer conversion, without Python Enum inheritance. It
   strips trailing whitespace and forces a single final newline, so the
   committed stubs already satisfy the whitespace hooks and keep matching
   generator output byte for byte.
3. ``gen_submodule_shims.py`` refreshes the ``.py`` shims that make the native
   submodules resolvable for a static type checker.

Only files carrying the generator's own header are post-processed, so a stub
written by hand is never touched.

Run with ``--check`` to report drift without leaving any change behind. The exit
code follows the autofix convention: 1 when anything was (or would be) changed,
0 when nothing moved. A failure of the cargo step exits 2 instead, so a caller
that treats drift as its own signal cannot mistake a broken build for a clean
tree.
"""

from __future__ import annotations

# standard library
import ast
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

# itofin library
import gen_submodule_shims  # noqa: E402

CRATE_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = CRATE_DIR.parent.parent
PKG_DIR = CRATE_DIR / "python" / "itofin"

MARKER = "automatically generated by pyo3_stub_gen"
CTOR = re.compile(r"^(?P<indent>[ \t]*)def __new__\(cls(?P<params>.*)\) -> .+:$")


def rewrite_constructor(line: str) -> str:
    m = CTOR.match(line)
    if m is None:
        return line
    return f"{m['indent']}def __init__(self{m['params']}) -> None:"


def rewrite_enums(text: str) -> str:
    """Describe fieldless PyO3 classes without promising Python Enum behavior."""
    lines = text.splitlines()
    replacements: dict[int, list[str]] = {}
    for node in ast.parse(text).body:
        if not isinstance(node, ast.ClassDef) or not any(
            ast.unparse(base) == "enum.Enum" for base in node.bases
        ):
            continue
        replacements[node.lineno - 1] = [f"class {node.name}:"]
        members = [member for member in node.body if isinstance(member, ast.Assign)]
        if not members:
            raise ValueError(f"generated enum {node.name} has no members")
        for member in members:
            if (
                len(member.targets) != 1
                or not isinstance(member.targets[0], ast.Name)
                or not isinstance(member.value, ast.Constant)
                or member.value.value is not Ellipsis
            ):
                raise ValueError(f"unsupported generated enum member in {node.name}")
            replacements[member.lineno - 1] = [
                f"    {member.targets[0].id}: typing.ClassVar[{node.name}]"
            ]
        replacements[members[-1].lineno - 1].extend([
            f"    def __new__(cls, _unconstructible: typing.NoReturn) -> {node.name}: ...",
            "    def __int__(self) -> builtins.int: ...",
            "    __hash__: typing.ClassVar[None]  # type: ignore[assignment]",
        ])
    rewritten = "\n".join(
        output for index, line in enumerate(lines)
        for output in replacements.get(index, [line])
    )
    if "enum." not in rewritten:
        rewritten = rewritten.replace("import enum\n", "")
    return rewritten


def post_process(text: str) -> str:
    text = rewrite_enums(text)
    lines = [rewrite_constructor(line).rstrip() for line in text.split("\n")]
    while lines and not lines[-1]:
        lines.pop()
    return "\n".join(lines) + "\n"


def snapshot(pkg_dir: Path) -> dict[Path, str]:
    return {p: p.read_text(encoding="utf-8") for p in sorted(pkg_dir.rglob("*.pyi"))}


def run_generator() -> None:
    subprocess.run(
        ["cargo", "run", "--quiet", "-p", "itofin-py", "--bin", "stub_gen"],
        cwd=REPO_ROOT,
        check=True,
    )


def post_process_generated(pkg_dir: Path) -> None:
    for pyi in sorted(pkg_dir.rglob("*.pyi")):
        current = pyi.read_text(encoding="utf-8")
        if MARKER not in current:
            continue
        wanted = post_process(current)
        if current != wanted:
            pyi.write_text(wanted, encoding="utf-8")


def restore(pkg_dir: Path, before: dict[Path, str]) -> None:
    for path in sorted(pkg_dir.rglob("*.pyi")):
        if path not in before:
            path.unlink()
    for path, text in before.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")


def describe(before: dict[Path, str], after: dict[Path, str], pkg_dir: Path) -> list[str]:
    changes: list[str] = []
    for path in sorted(set(before) | set(after)):
        name = path.relative_to(pkg_dir)
        if path not in before:
            changes.append(f"new: {name}")
        elif path not in after:
            changes.append(f"orphaned: {name}")
        elif before[path] != after[path]:
            changes.append(f"stale: {name}")
    return changes


def main() -> int:
    args = [a for a in sys.argv[1:] if a.startswith("--")]
    check = "--check" in args

    before = snapshot(PKG_DIR)
    try:
        run_generator()
    except subprocess.CalledProcessError as exc:
        print(f"stub generator failed: {exc}", file=sys.stderr)
        return 2
    post_process_generated(PKG_DIR)
    after = snapshot(PKG_DIR)
    changes = describe(before, after, PKG_DIR)
    if check:
        restore(PKG_DIR, before)

    if changes:
        verb = "would update" if check else "updated"
        print(f"generated stubs {verb}:", file=sys.stderr)
        for c in changes:
            print(f"  {c}", file=sys.stderr)

    shims = gen_submodule_shims.run(PKG_DIR, check=check)
    return 1 if (changes or shims) else 0


if __name__ == "__main__":
    raise SystemExit(main())
