#!/usr/bin/env python3
"""Transcribe QuantLib Sobol / lattice static data tables into generated Rust files.

Reads the C++ sources under QuantLib/ql/math/randomnumbers and emits Rust
statics under crates/libitofin/src/math/randomnumbers. Large tables are split
into multiple data files so every generated file stays under the pre-commit
large-file limit (1024 KB).

Usage: python3 scripts/gen_sobol_tables.py [--quantlib DIR] [--out DIR]
"""

# standard library
import argparse
import pathlib
import re
import subprocess
import sys

HEADER = "// @generated by scripts/gen_sobol_tables.py - do not edit by hand.\n"
MAX_DATA_FILE_BYTES = 900_000
VALUES_PER_LINE = 16

EXPECTED_DEGREE_COUNTS = [
    1, 1, 2, 2, 6, 6, 18, 16, 48, 60, 176, 144, 630, 756, 1800, 2048, 7710, 7776,
]
EXPECTED_TABLE_DIMS = {
    "initializers": 31,
    "SLinitializers": 39,
    "Linitializers": 359,
    "Kuoinitializers": 4925,
    "Kuo2initializers": 3946,
    "Kuo3initializers": 4586,
    "JoeKuoD5initializers": 1999,
    "JoeKuoD6initializers": 21200,
    "JoeKuoD7initializers": 1899,
}
RUST_TABLE_NAMES = {
    "initializers": "jaeckel",
    "SLinitializers": "sobol_levitan",
    "Linitializers": "lemieux",
    "Kuoinitializers": "kuo",
    "Kuo2initializers": "kuo2",
    "Kuo3initializers": "kuo3",
    "JoeKuoD5initializers": "joe_kuo_d5",
    "JoeKuoD6initializers": "joe_kuo_d6",
    "JoeKuoD7initializers": "joe_kuo_d7",
}


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
    return re.sub(r"//[^\n]*", " ", text)


def parse_int_arrays(text, decl_pattern):
    arrays = {}
    for match in re.finditer(decl_pattern, text, flags=re.S):
        name, body = match.group(1), match.group(2)
        values = [int(tok) for tok in re.findall(r"-?\d+", body)]
        arrays[name] = values
    return arrays


def parse_pointer_tables(text):
    tables = {}
    pattern = r"const\s+std::uint32_t\s*\*\s*const\s+(\w+)\[\s*\d*\s*\]\s*=?\s*\{(.*?)\};"
    for match in re.finditer(pattern, text, flags=re.S):
        name, body = match.group(1), match.group(2)
        tables[name] = re.findall(r"[A-Za-z_]\w*", body)
    return tables


def take_terminated(name, values, terminator):
    if not values or values[-1] != terminator:
        sys.exit(f"{name}: expected trailing {terminator} terminator")
    body = values[:-1]
    if terminator in body:
        sys.exit(f"{name}: unexpected interior terminator {terminator}")
    return body


def format_values(values, suffix=""):
    lines = []
    for start in range(0, len(values), VALUES_PER_LINE):
        chunk = values[start : start + VALUES_PER_LINE]
        lines.append("    " + " ".join(f"{v}{suffix}," for v in chunk))
    return "\n".join(lines)


WRITTEN = []


def write_file(path, body):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(HEADER + "\n" + body)
    WRITTEN.append(path)
    size = path.stat().st_size
    if size > 1024 * 1000:
        sys.exit(f"{path}: generated file is {size} bytes, over the 1024 KB limit")
    print(f"  wrote {path} ({size} bytes)")


def split_entries(entries):
    parts, current, current_bytes = [], [], 0
    for entry in entries:
        entry_bytes = sum(len(str(v)) + 2 for v in entry)
        if current and current_bytes + entry_bytes > MAX_DATA_FILE_BYTES:
            parts.append(current)
            current, current_bytes = [], 0
        current.append(entry)
        current_bytes += entry_bytes
    parts.append(current)
    return parts


def emit_initializer_table(out_dir, rust_name, entries):
    offsets, total = [0], 0
    for entry in entries:
        total += len(entry)
        offsets.append(total)
    upper = rust_name.upper()
    parts = split_entries(entries)
    part_names = []
    for i, part in enumerate(parts):
        module = f"{rust_name}_data_{i}"
        part_names.append(module)
        flat = [v for entry in part for v in entry]
        body = (
            "#[rustfmt::skip]\n"
            f"pub(super) static DATA: &[u32] = &[\n{format_values(flat)}\n];\n"
        )
        write_file(out_dir / f"{module}.rs", body)
    body = (
        "#[rustfmt::skip]\n"
        f"pub(super) static OFFSETS: &[u32] = &[\n{format_values(offsets)}\n];\n"
    )
    write_file(out_dir / f"{rust_name}_offsets.rs", body)
    modules = [f"mod {name};" for name in part_names + [f"{rust_name}_offsets"]]
    statics = (
        f"pub(crate) static {upper}_OFFSETS: &[u32] = {rust_name}_offsets::OFFSETS;\n"
        f"pub(crate) static {upper}_PARTS: &[&[u32]] = &[{', '.join(f'{m}::DATA' for m in part_names)}];\n"
    )
    return modules, statics


def emit_polynomials(out_dir, degrees, alt_degrees):
    sections = []
    for i, values in enumerate(degrees, start=1):
        sections.append(
            "#[rustfmt::skip]\n"
            f"static DEGREE_{i:02}: &[u32] = &[\n{format_values(values)}\n];"
        )
    for i, values in enumerate(alt_degrees, start=1):
        sections.append(
            "#[rustfmt::skip]\n"
            f"static ALT_DEGREE_{i:02}: &[u32] = &[\n{format_values(values)}\n];"
        )
    ppmt_max_dim = sum(len(v) for v in degrees)
    max_alt = sum(len(v) for v in alt_degrees)
    master = ", ".join(f"DEGREE_{i:02}" for i in range(1, len(degrees) + 1))
    alt_master = ", ".join(f"ALT_DEGREE_{i:02}" for i in range(1, len(alt_degrees) + 1))
    sections.append(f"pub(crate) const PPMT_MAX_DIM: usize = {ppmt_max_dim};")
    sections.append(f"pub(crate) const MAX_ALT_POLYNOMIALS: usize = {max_alt};")
    sections.append(
        f"pub(crate) static PRIMITIVE_POLYNOMIALS: [&[u32]; {len(degrees)}] = [{master}];"
    )
    sections.append(
        f"pub(crate) static ALT_PRIMITIVE_POLYNOMIALS: [&[u32]; {len(alt_degrees)}] = [{alt_master}];"
    )
    write_file(out_dir / "primitive_polynomials.rs", "\n\n".join(sections) + "\n")


def emit_lattices(out_dir, lattices):
    sections = []
    for name in "ABCD":
        values = lattices[f"lattice{name}"]
        formatted = format_values(values, suffix=".0")
        sections.append(
            "#[rustfmt::skip]\n"
            f"pub(crate) static LATTICE_{name}: &[f64] = &[\n{formatted}\n];"
        )
    write_file(out_dir / "lattice_tables.rs", "\n\n".join(sections) + "\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--quantlib", default="QuantLib/ql/math/randomnumbers")
    parser.add_argument("--out", default="crates/libitofin/src/math/randomnumbers")
    args = parser.parse_args()
    src = pathlib.Path(args.quantlib)
    out = pathlib.Path(args.out)
    tables_dir = out / "sobol" / "tables"

    print("parsing primitivepolynomials.cpp")
    text = strip_comments((src / "primitivepolynomials.cpp").read_text(encoding="latin-1"))
    arrays = parse_int_arrays(
        text, r"static\s+const\s+long\s+(PrimitivePolynomialDegree\d+)\[\]\s*=\s*\{(.*?)\};"
    )
    degrees = []
    for i in range(1, len(arrays) + 1):
        values = take_terminated(f"degree {i}", arrays[f"PrimitivePolynomialDegree{i:02}"], -1)
        if len(values) != EXPECTED_DEGREE_COUNTS[i - 1]:
            sys.exit(f"degree {i}: {len(values)} polynomials, expected {EXPECTED_DEGREE_COUNTS[i - 1]}")
        degrees.append(values)

    print("parsing sobolrsg.cpp")
    text = strip_comments((src / "sobolrsg.cpp").read_text(encoding="latin-1"))
    alt_arrays = parse_int_arrays(
        text, r"const\s+long\s+(AltPrimitivePolynomialDegree\d+)\[\]\s*=\s*\{(.*?)\};"
    )
    alt_degrees = [
        take_terminated(f"alt degree {i}", alt_arrays[f"AltPrimitivePolynomialDegree{i:02}"], -1)
        for i in range(1, len(alt_arrays) + 1)
    ]
    if sum(len(v) for v in alt_degrees) != 52:
        sys.exit("alternative polynomials: expected 52 entries in total")
    dim_arrays = {
        name: take_terminated(name, values, 0)
        for name, values in parse_int_arrays(
            text, r"const\s+std::uint32_t\s+(\w+)\[\]\s*=\s*\{(.*?)\};"
        ).items()
    }
    pointer_tables = parse_pointer_tables(text)

    emit_polynomials(tables_dir, degrees, alt_degrees)
    mod_lines, static_lines = [], []
    for cpp_name, rust_name in RUST_TABLE_NAMES.items():
        members = pointer_tables[cpp_name]
        if len(members) != EXPECTED_TABLE_DIMS[cpp_name]:
            sys.exit(f"{cpp_name}: {len(members)} dimensions, expected {EXPECTED_TABLE_DIMS[cpp_name]}")
        entries = [dim_arrays[member] for member in members]
        modules, statics = emit_initializer_table(tables_dir, rust_name, entries)
        mod_lines.extend(modules)
        static_lines.append(statics)
    mod_body = (
        "mod primitive_polynomials;\n"
        + "\n".join(sorted(mod_lines))
        + "\n\npub(crate) use primitive_polynomials::{\n"
        + "    ALT_PRIMITIVE_POLYNOMIALS, MAX_ALT_POLYNOMIALS, PPMT_MAX_DIM, PRIMITIVE_POLYNOMIALS,\n"
        + "};\n\n"
        + "\n".join(static_lines)
    )
    write_file(tables_dir / "mod.rs", mod_body)

    print("parsing latticerules.cpp")
    text = strip_comments((src / "latticerules.cpp").read_text(encoding="latin-1"))
    lattices = parse_int_arrays(text, r"const\s+Real\s+(lattice[ABCD])\[\]\s*=\s*\{(.*?)\};")
    for name, values in lattices.items():
        if len(values) != 3600:
            sys.exit(f"{name}: {len(values)} values, expected exactly 3600")
    emit_lattices(out, lattices)
    subprocess.run(
        ["rustfmt", "--edition", "2024"] + [str(p) for p in WRITTEN], check=True
    )
    print("done")


if __name__ == "__main__":
    main()
