# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "SimpleQuote",
]

@typing.final
class SimpleQuote:
    r"""
    A mutable, observable market element (D1).

    Wraps a single value that pricing inputs observe; setting a new value
    notifies dependents so any cached valuation recomputes lazily.
    """
    def __init__(self, value: builtins.float) -> None:
        r"""
        Initialize the quote.

        Args:
            value (float): The initial market value.
        """
    def value(self) -> builtins.float:
        r"""
        Return the current value.

        Fallible: a quote whose value was never set raises ItofinError.

        Returns:
            float: The quote's current market value.
        """
    def set_value(self, value: builtins.float) -> None:
        r"""
        Set a new value and notify observers.

        Args:
            value (float): The new value; observers are notified when it actually
                changes, so dependent valuations recompute on next access.
        """
