"""Runtime source shim for the native ``itofin.optimize`` submodule.

The real ``itofin.optimize`` is a compiled submodule registered into
``sys.modules`` by the extension; it wins at import time, so nothing here
runs. This file exists only so static type checkers resolve
``from itofin.optimize import ...`` from ``optimize/__init__.pyi`` without a
``reportMissingModuleSource`` warning.

Auto-generated by scripts/gen_submodule_shims.py from ``optimize/__init__.pyi``; do not edit or delete by hand.
"""
