# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "ConvergenceStatistics",
    "DrawdownResult",
    "GeneralStatistics",
    "IncrementalStatistics",
    "average_shortfall",
    "benchmark_beta",
    "convergence_table",
    "correlation_matrix",
    "covariance_matrix",
    "discrepancy",
    "downside_deviation",
    "downside_variance",
    "expected_shortfall",
    "maximum_drawdown",
    "mean",
    "percentile",
    "potential_upside",
    "regret",
    "semi_deviation",
    "semi_variance",
    "sequence_error_estimate",
    "sequence_maximum",
    "sequence_mean",
    "sequence_minimum",
    "sequence_standard_deviation",
    "sequence_variance",
    "sharpe_ratio",
    "shortfall",
    "sortino_ratio",
    "standard_deviation",
    "target_downside_deviation",
    "top_percentile",
    "value_at_risk",
    "variance",
]

@typing.final
class ConvergenceStatistics:
    r"""
    Atomic bounded accumulator for cumulative mean-convergence diagnostics.
    """
    def __init__(self) -> None:
        r"""
        Construct an empty accumulator with checkpoints 1, 3, 7, 15, and so on.
        """
    def add(self, value: builtins.float, weight: builtins.float = 1.0) -> None:
        r"""
        Add one finite observation atomically with a nonnegative finite weight.
        """
    def add_batch(self, observations: typing.Sequence[builtins.float], *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> None:
        r"""
        Add a complete ordered batch atomically; omitted weights are one.
        """
    def reset(self) -> None:
        r"""
        Clear every sample and checkpoint.
        """
    def samples(self) -> builtins.int:
        r"""
        Number of accepted observations, including zero-weight observations.
        """
    def weight_sum(self) -> builtins.float:
        r"""
        Sum of accepted weights.
        """
    def mean(self) -> builtins.float:
        r"""
        Weighted mean of all accepted observations, including an incomplete prefix.
        """
    def convergence_table(self) -> builtins.list[tuple[builtins.int, builtins.float]]:
        r"""
        Return a fresh list of immutable sample-count and cumulative-mean tuples.
        """

@typing.final
class DrawdownResult:
    r"""
    Immutable fractional maximum loss and zero-based ordered NAV indices.
    """
    @property
    def drawdown(self) -> builtins.float:
        r"""
        Nonnegative fractional loss, not a signed return or percentage.
        """
    @property
    def peak_index(self) -> builtins.int:
        r"""
        Earliest equal running peak before the winning trough.
        """
    @property
    def trough_index(self) -> builtins.int:
        r"""
        First trough attaining the greatest computed fractional loss.
        """

@typing.final
class GeneralStatistics:
    r"""
    Stores weighted observations and exposes empirical moments and risk measures.
    A zero-weight observation counts toward count-based moment corrections.
    """
    def __init__(self) -> None:
        r"""
        Create an empty stored-sample accumulator.
        """
    def add(self, value: builtins.float, weight: builtins.float = 1.0) -> None:
        r"""
        Add one finite observation with a nonnegative weight.
        """
    def add_batch(self, observations: typing.Sequence[builtins.float], *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> None:
        r"""
        Atomically append a sequence and optional matching weights.
        """
    def reset(self) -> None:
        r"""
        Remove all observations.
        """
    def samples(self) -> builtins.int:
        r"""
        Number of observations, including zero-weight observations.
        """
    def weight_sum(self) -> builtins.float:
        r"""
        Sum of observation weights.
        """
    def min(self) -> builtins.float: ...
    def max(self) -> builtins.float: ...
    def mean(self) -> builtins.float: ...
    def variance(self) -> builtins.float: ...
    def standard_deviation(self) -> builtins.float: ...
    def error_estimate(self) -> builtins.float: ...
    def skewness(self) -> builtins.float: ...
    def kurtosis(self) -> builtins.float: ...
    def percentile(self, probability: builtins.float) -> builtins.float: ...
    def top_percentile(self, probability: builtins.float) -> builtins.float: ...
    def semi_variance(self) -> builtins.float: ...
    def semi_deviation(self) -> builtins.float: ...
    def downside_variance(self) -> builtins.float: ...
    def downside_deviation(self) -> builtins.float: ...
    def regret(self, target: builtins.float) -> builtins.float: ...
    def potential_upside(self, confidence: builtins.float) -> builtins.float: ...
    def value_at_risk(self, confidence: builtins.float) -> builtins.float: ...
    def expected_shortfall(self, confidence: builtins.float) -> builtins.float: ...
    def shortfall(self, target: builtins.float) -> builtins.float: ...
    def average_shortfall(self, target: builtins.float) -> builtins.float: ...

@typing.final
class IncrementalStatistics:
    r"""
    Weighted streaming moments with fixed memory use, independent of sample count.
    """
    def __init__(self) -> None:
        r"""
        Create an empty accumulator.
        """
    def add(self, value: builtins.float, weight: builtins.float = 1.0) -> None:
        r"""
        Append one finite observation and finite nonnegative weight.
        """
    def add_batch(self, values: typing.Sequence[builtins.float], *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> None:
        r"""
        Append a batch atomically; omitted weights give unit weights.
        """
    def reset(self) -> None:
        r"""
        Clear all observations while retaining this object.
        """
    def samples(self) -> builtins.int:
        r"""
        Number of observations, including zero-weight observations.
        """
    def downside_samples(self) -> builtins.int:
        r"""
        Number of strictly negative observations.
        """
    def weight_sum(self) -> builtins.float:
        r"""
        Sum of all observation weights.
        """
    def downside_weight_sum(self) -> builtins.float:
        r"""
        Sum of weights on strictly negative observations.
        """
    def min(self) -> builtins.float:
        r"""
        Lowest observation.
        """
    def max(self) -> builtins.float:
        r"""
        Highest observation.
        """
    def mean(self) -> builtins.float:
        r"""
        Weighted arithmetic mean.
        """
    def variance(self) -> builtins.float:
        r"""
        Weighted variance corrected by the sample count N/(N-1).
        """
    def standard_deviation(self) -> builtins.float:
        r"""
        Square root of the corrected variance.
        """
    def error_estimate(self) -> builtins.float:
        r"""
        Standard error of the mean.
        """
    def skewness(self) -> builtins.float:
        r"""
        Bias-corrected weighted skewness.
        """
    def kurtosis(self) -> builtins.float:
        r"""
        Bias-corrected excess kurtosis.
        """
    def downside_variance(self) -> builtins.float:
        r"""
        Corrected second moment of strictly negative observations.
        """
    def downside_deviation(self) -> builtins.float:
        r"""
        Square root of the downside variance.
        """

def average_shortfall(observations: typing.Sequence[builtins.float], target: builtins.float, *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.float:
    r"""
    Weighted mean of target minus observations strictly below target.
    """

def benchmark_beta(asset_returns: typing.Sequence[builtins.float], benchmark_returns: typing.Sequence[builtins.float], *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.float:
    r"""
    Weighted covariance / benchmark variance for 2-100000 aligned return pairs.

    No annualization, data feed or risk-free adjustment. Weights are optional,
    finite and nonnegative with finite positive total. Both moments apply the
    same observation-count correction, counting zero-weight rows. All samples
    must be finite; zero benchmark variance or nonfinite moments/beta raise
    ItofinError. Caller owns date/frequency alignment. Inputs are unchanged;
    no native handle or context needs closing.
    """

def convergence_table(observations: typing.Sequence[builtins.float], *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.list[tuple[builtins.int, builtins.float]]:
    r"""
    Cumulative weighted means at checkpoints 1, 3, 7, 15, and so on.

    The incomplete final prefix is not recorded. Input order is preserved;
    zero-weight observations count, but every checkpoint needs positive weight.
    """

def correlation_matrix(samples: typing.Sequence[typing.Sequence[builtins.float]], *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.list[builtins.list[builtins.float]]:
    r"""
    Correlations with unit diagonal, both constant components one, exactly one constant zero.
    """

def covariance_matrix(samples: typing.Sequence[typing.Sequence[builtins.float]], *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.list[builtins.list[builtins.float]]:
    r"""
    Symmetric weighted covariance matrix with row-count correction n/(n-1).
    """

def discrepancy(samples: typing.Sequence[typing.Sequence[builtins.float]], *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.float:
    r"""
    Star L2 discrepancy of rectangular samples in the closed unit cube.

    Only omitted weights or exact unit weights are supported. Shape and work
    bounds are checked before flattening; Python argument extraction occurs first.
    """

def downside_deviation(observations: typing.Sequence[builtins.float], *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.float:
    r"""
    Square root of downside variance.
    """

def downside_variance(observations: typing.Sequence[builtins.float], *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.float:
    r"""
    Count-corrected conditional variance below zero.
    """

def expected_shortfall(observations: typing.Sequence[builtins.float], confidence: builtins.float, *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.float:
    r"""
    Weighted mean loss strictly below the VaR threshold, as a positive magnitude.
    """

def maximum_drawdown(values: typing.Sequence[builtins.float]) -> DrawdownResult:
    r"""
    Maximum drawdown of ordered finite strictly positive equity/NAV values.

    Empty input errors. One NAV or no decline returns zero with indices (0, 0).
    Equal peaks retain their earliest index; equal computed losses retain the
    first trough. Extreme positive ratios may round the fractional loss to one.
    This is not meaningful for unordered return samples. Results own no handles.
    """

def mean(observations: typing.Sequence[builtins.float], *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.float:
    r"""
    Weighted mean of signed observations. Negative observations represent losses.
    """

def percentile(observations: typing.Sequence[builtins.float], probability: builtins.float, *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.float:
    r"""
    Weighted empirical percentile for a probability in (0, 1].
    """

def potential_upside(observations: typing.Sequence[builtins.float], confidence: builtins.float, *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.float:
    r"""
    Nonnegative upper percentile at confidence in [0.9, 1).
    """

def regret(observations: typing.Sequence[builtins.float], target: builtins.float, *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.float:
    r"""
    Count-corrected conditional variance below a finite target.
    """

def semi_deviation(observations: typing.Sequence[builtins.float], *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.float:
    r"""
    Square root of semi variance.
    """

def semi_variance(observations: typing.Sequence[builtins.float], *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.float:
    r"""
    Count-corrected conditional variance below the weighted mean.
    """

def sequence_error_estimate(samples: typing.Sequence[typing.Sequence[builtins.float]], *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.list[builtins.float]:
    r"""
    Component standard errors using the total row count, including zero-weight rows.
    """

def sequence_maximum(samples: typing.Sequence[typing.Sequence[builtins.float]], *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.list[builtins.float]:
    r"""
    Component maxima over all rows, including zero-weight rows.
    """

def sequence_mean(samples: typing.Sequence[typing.Sequence[builtins.float]], *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.list[builtins.float]:
    r"""
    Weighted component means of rectangular row samples.
    """

def sequence_minimum(samples: typing.Sequence[typing.Sequence[builtins.float]], *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.list[builtins.float]:
    r"""
    Component minima over all rows, including zero-weight rows.
    """

def sequence_standard_deviation(samples: typing.Sequence[typing.Sequence[builtins.float]], *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.list[builtins.float]:
    r"""
    Square roots of the count-corrected component variances.
    """

def sequence_variance(samples: typing.Sequence[typing.Sequence[builtins.float]], *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.list[builtins.float]:
    r"""
    Component variances with row-count correction n/(n-1), including zero-weight rows.
    """

def sharpe_ratio(returns: typing.Sequence[builtins.float], risk_free_return: builtins.float, *, periods_per_year: builtins.float) -> builtins.float:
    r"""
    Arithmetic excess mean/sample std (N-1), scaled by sqrt(periods_per_year).
    Risk-free return is per period. Frequency is required; zero dispersion is an error.
    """

def shortfall(observations: typing.Sequence[builtins.float], target: builtins.float, *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.float:
    r"""
    Weighted probability of observations strictly below a finite target.
    """

def sortino_ratio(returns: typing.Sequence[builtins.float], minimum_acceptable_return: builtins.float, *, periods_per_year: builtins.float) -> builtins.float:
    r"""
    Arithmetic mean minus per-period MAR/all-N downside, scaled by sqrt(periods_per_year).
    Frequency is required; no downside is an error, not infinity.
    """

def standard_deviation(observations: typing.Sequence[builtins.float], *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.float:
    r"""
    Square root of weighted sample variance.
    """

def target_downside_deviation(returns: typing.Sequence[builtins.float], target: builtins.float) -> builtins.float:
    r"""
    All-observation RMS shortfall below the scalar per-period target, without annualization.
    """

def top_percentile(observations: typing.Sequence[builtins.float], probability: builtins.float, *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.float:
    r"""
    Weighted empirical percentile traversing observations from high to low.
    """

def value_at_risk(observations: typing.Sequence[builtins.float], confidence: builtins.float, *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.float:
    r"""
    Loss magnitude at confidence in [0.9, 1), capped at zero for gains.
    """

def variance(observations: typing.Sequence[builtins.float], *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.float:
    r"""
    Weighted sample variance with the core's count-based n/(n-1) correction.
    """
