# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "expected_shortfall",
    "mean",
    "percentile",
    "standard_deviation",
    "value_at_risk",
    "variance",
]

def expected_shortfall(observations: typing.Sequence[builtins.float], confidence: builtins.float, *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.float:
    r"""
    Weighted mean loss strictly below the VaR threshold, as a positive magnitude.
    """

def mean(observations: typing.Sequence[builtins.float], *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.float:
    r"""
    Weighted mean of signed observations. Negative observations represent losses.
    """

def percentile(observations: typing.Sequence[builtins.float], probability: builtins.float, *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.float:
    r"""
    Weighted empirical percentile for a probability in (0, 1].
    """

def standard_deviation(observations: typing.Sequence[builtins.float], *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.float:
    r"""
    Square root of weighted sample variance.
    """

def value_at_risk(observations: typing.Sequence[builtins.float], confidence: builtins.float, *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.float:
    r"""
    Loss magnitude at confidence in [0.9, 1), capped at zero for gains.
    """

def variance(observations: typing.Sequence[builtins.float], *, weights: typing.Optional[typing.Sequence[builtins.float]] = None) -> builtins.float:
    r"""
    Weighted sample variance with the core's count-based n/(n-1) correction.
    """
